[CmdletBinding()]
param(
    [string] $ProjectRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($ProjectRoot)) {
    $ProjectRoot = Split-Path -Parent $PSScriptRoot
}

function Assert-Contains {
    param(
        [Parameter(Mandatory)] [string] $Path,
        [Parameter(Mandatory)] [string] $Pattern,
        [Parameter(Mandatory)] [string] $Description
    )

    if (-not (Select-String -Path $Path -Pattern $Pattern -Quiet)) {
        throw "${Description}: '$Pattern' was not found in $Path."
    }
}

function Assert-NotContains {
    param(
        [Parameter(Mandatory)] [string] $Path,
        [Parameter(Mandatory)] [string] $Pattern,
        [Parameter(Mandatory)] [string] $Description
    )

    if (Select-String -Path $Path -Pattern $Pattern -Quiet) {
        throw "${Description}: '$Pattern' must not be present in $Path."
    }
}

function Assert-OrderedPatterns {
    param(
        [Parameter(Mandatory)] [string] $Path,
        [Parameter(Mandatory)] [string[]] $Patterns,
        [Parameter(Mandatory)] [string] $Description
    )

    $content = Get-Content -Raw $Path
    $offset = 0
    foreach ($pattern in $Patterns) {
        $match = [regex]::Match($content.Substring($offset), $pattern)
        if (-not $match.Success) {
            throw "${Description}: '$pattern' was not found in order in $Path."
        }
        $offset += $match.Index + $match.Length
    }
}

$projectDir = Join-Path $ProjectRoot 'mspm0g3507_app'
$main = Join-Path $projectDir 'main.c'
$ws2812 = Join-Path $projectDir 'board_ws2812.c'
$ws2812Header = Join-Path $projectDir 'board_ws2812.h'
$buzzer = Join-Path $projectDir 'board_buzzer.c'
$buzzerHeader = Join-Path $projectDir 'board_buzzer.h'
$bmi160 = Join-Path $projectDir 'board_bmi160.c'
$bmi160Header = Join-Path $projectDir 'board_bmi160.h'
$imuYaw = Join-Path $projectDir 'board_imu_yaw.c'
$imuYawHeader = Join-Path $projectDir 'board_imu_yaw.h'
$buttons = Join-Path $projectDir 'board_buttons.c'
$buttonsHeader = Join-Path $projectDir 'board_buttons.h'
$grayscale = Join-Path $projectDir 'board_grayscale.c'
$grayscaleHeader = Join-Path $projectDir 'board_grayscale.h'
$lineTracking = Join-Path $projectDir 'line_tracking.c'
$lineTrackingHeader = Join-Path $projectDir 'line_tracking.h'
$openKeilScript = Join-Path $ProjectRoot 'tools\open-keil-mspm0g3507-app.ps1'
$uart = Join-Path $projectDir 'board_uart.c'
$motor = Join-Path $projectDir 'board_motor.c'
$motorHeader = Join-Path $projectDir 'board_motor.h'
$encoder = Join-Path $projectDir 'board_encoder.c'
$encoderHeader = Join-Path $projectDir 'board_encoder.h'
$motorControl = Join-Path $projectDir 'motor_control.c'
$motorControlHeader = Join-Path $projectDir 'motor_control.h'
$motorPid = Join-Path $projectDir 'motor_pid\pid.c'
$motorPidHeader = Join-Path $projectDir 'motor_pid\pid.h'
$vofaJustFloat = Join-Path $projectDir 'vofa_justfloat.c'
$vofaJustFloatHeader = Join-Path $projectDir 'vofa_justfloat.h'
$syscfg = Join-Path $projectDir 'mspm0g3507_app.syscfg'
$rtosConfig = Join-Path $projectDir 'FreeRTOSConfig.h'
$ccsBuildConfig = Join-Path $projectDir '.cproject'
$buildScript = Join-Path $ProjectRoot 'tools\build-mspm0g3507-app.ps1'
$flashScript = Join-Path $ProjectRoot 'tools\flash-and-debug-g3507.ps1'
$tasks = Join-Path $ProjectRoot '.vscode\tasks.json'
$launch = Join-Path $ProjectRoot '.vscode\launch.json'
$gitIgnore = Join-Path $ProjectRoot '.gitignore'

foreach ($path in @($projectDir, $main, $ws2812, $ws2812Header, $buzzer, $buzzerHeader, $bmi160, $bmi160Header, $imuYaw, $imuYawHeader, $buttons, $buttonsHeader, $grayscale, $grayscaleHeader, $lineTracking, $lineTrackingHeader, $uart, $motor, $motorHeader, $encoder, $encoderHeader, $motorControl, $motorControlHeader, $motorPid, $motorPidHeader, $vofaJustFloat, $vofaJustFloatHeader, $syscfg, $rtosConfig, $ccsBuildConfig,
                        $buildScript, $flashScript, $tasks, $launch, $gitIgnore)) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "MSPM0G3507 app project is incomplete: $path is missing."
    }
}

Assert-Contains -Path $main -Pattern 'xTaskCreateStatic' -Description 'WS2812 and UART tasks must use static allocation'
Assert-Contains -Path $main -Pattern 'xQueueCreateStatic' -Description 'UART queue must use static allocation'
Assert-Contains -Path $main -Pattern 'pdMS_TO_TICKS\(500U\)' -Description 'WS2812 animation must update every 500 ms'
Assert-Contains -Path $main -Pattern 'WS2812_BRIGHTNESS\s+\d+U' -Description 'WS2812 animation must define a channel brightness'
Assert-Contains -Path $main -Pattern 'board_ws2812_write' -Description 'WS2812 animation must submit frames'
Assert-Contains -Path $main -Pattern 'pdMS_TO_TICKS\(10U\)' -Description 'Motor task must refresh commands every 10 ms'
Assert-Contains -Path $main -Pattern 'xTaskCreateStatic\(motor_task' -Description 'Motor task must use static allocation'
Assert-Contains -Path $main -Pattern 'board_encoder_init' -Description 'Application must initialize the encoder driver'
Assert-Contains -Path $main -Pattern 'motor_control_init' -Description 'Application must initialize the motor control layer'
Assert-Contains -Path $main -Pattern 'motor_control_step' -Description 'Motor task must run the motor control layer'
Assert-OrderedPatterns -Path $main -Patterns @('board_encoder_sample', 'motor_control_step', 'board_motor_set_signed_duty') -Description 'Motor task must sample encoders, calculate control, then update PWM'
Assert-Contains -Path $main -Pattern 'GROUP1_IRQHandler' -Description 'Application must provide the GPIOA interrupt handler for encoder A phases'
Assert-Contains -Path $main -Pattern 'g_encoder_samples' -Description 'Application must retain encoder samples for debugger observation'
Assert-Contains -Path $main -Pattern 'VOFA_SPEED_PID_TELEMETRY_INTERVAL_MS\s+10U' -Description 'VOFA speed PID telemetry must run at 100 Hz'
Assert-Contains -Path $main -Pattern 'VOFA_SPEED_PID_TELEMETRY_TASK_STACK_DEPTH\s+256U' -Description 'VOFA telemetry task must have a static stack'
Assert-Contains -Path $main -Pattern '#ifndef VOFA_SPEED_PID_TELEMETRY_ENABLE' -Description 'VOFA speed PID telemetry must remain build-configurable'
Assert-Contains -Path $main -Pattern '#define VOFA_SPEED_PID_TELEMETRY_ENABLE 0U' -Description 'VOFA speed PID telemetry must default to disabled'
Assert-Contains -Path $main -Pattern '#if VOFA_SPEED_PID_TELEMETRY_ENABLE' -Description 'VOFA telemetry task must be compile-time gated'
Assert-Contains -Path $main -Pattern 'VOFA_SPEED_PID_TELEMETRY_ENABLE &&' -Description 'VOFA telemetry modes must be mutually exclusive'
Assert-Contains -Path $main -Pattern '#error.*cannot be enabled together' -Description 'Mutually enabled VOFA modes must be rejected at compile time'
Assert-NotContains -Path $main -Pattern 'ENCODER_TELEMETRY_ENABLE' -Description 'Legacy encoder telemetry switch must be removed'
Assert-NotContains -Path $main -Pattern 'ctl,fl=' -Description 'Legacy text control telemetry must be removed'
Assert-Contains -Path $main -Pattern 'telemetry_task' -Description 'Application must provide a VOFA telemetry task'
Assert-Contains -Path $main -Pattern 'xTaskCreateStatic\(telemetry_task' -Description 'VOFA telemetry task must use static allocation'
Assert-Contains -Path $main -Pattern 'vofa_justfloat_encode3' -Description 'VOFA telemetry must encode JustFloat frames'
Assert-OrderedPatterns -Path $main -Patterns @('target_speed_mm_per_s', 'feedback_speed_mm_per_s', 'output_duty_percent') -Description 'VOFA channels must remain target speed, feedback speed, then output duty'
Assert-Contains -Path $main -Pattern 'g_motor_debug\.wheel' -Description 'VOFA telemetry must follow the SWD debug wheel'
Assert-Contains -Path $main -Pattern 'wheel >= BOARD_MOTOR_COUNT' -Description 'VOFA telemetry must fall back from an invalid debug wheel'
Assert-Contains -Path $main -Pattern 'board_uart_write\(frame, sizeof\(frame\)\)' -Description 'VOFA telemetry must send whole frames through the serialized UART writer'
Assert-Contains -Path $main -Pattern '#if !VOFA_SPEED_PID_TELEMETRY_ENABLE && !GRAY_VOFA_TELEMETRY_ENABLE' -Description 'VOFA modes must compile out the UART echo task'
Assert-Contains -Path $main -Pattern 'xTaskCreateStatic\(board_uart_tx_task' -Description 'Application must create the dedicated UART transmit task'
Assert-Contains -Path $main -Pattern 'IMU_TASK_STACK_DEPTH\s+512U' -Description 'IMU task must have a static stack'
Assert-Contains -Path $main -Pattern 'IMU_SAMPLE_INTERVAL_MS\s+10U' -Description 'IMU task must sample every 10 ms'
Assert-Contains -Path $main -Pattern 'IMU_TELEMETRY_ENABLE\s+0U' -Description 'IMU telemetry must default to disabled'
Assert-Contains -Path $main -Pattern 'VOFA telemetry modes cannot be enabled together' -Description 'IMU and VOFA telemetry must be mutually exclusive'
Assert-Contains -Path $main -Pattern 'IMU telemetry requires IMU yaw to be enabled' -Description 'IMU telemetry must require yaw'
Assert-Contains -Path $main -Pattern 'IMU_YAW_ENABLE\s+0U' -Description 'IMU yaw must default to disabled'
Assert-Contains -Path $main -Pattern 'IMU_YAW_TRACK_WIDTH_MM\s+130\.0f' -Description 'IMU yaw must use the measured track width'
Assert-Contains -Path $main -Pattern '#if IMU_YAW_ENABLE' -Description 'IMU yaw integration must be compile-time gated'
Assert-Contains -Path $main -Pattern 'encoder_samples_snapshot_copy' -Description 'IMU yaw must use a coherent encoder snapshot'
Assert-Contains -Path $main -Pattern 'board_bmi160_init' -Description 'IMU task must initialize the BMI160 driver'
Assert-Contains -Path $main -Pattern 'board_bmi160_read_sample' -Description 'IMU task must read BMI160 samples'
Assert-Contains -Path $main -Pattern 'xTaskCreateStatic\(imu_task' -Description 'IMU task must use static allocation'
Assert-Contains -Path $main -Pattern 'board_bmi160_init' -Description 'IMU task must initialize the BMI160 driver'
Assert-Contains -Path $main -Pattern 'board_bmi160_read_sample' -Description 'IMU task must read BMI160 samples'
Assert-Contains -Path $main -Pattern 'xTaskCreateStatic\(imu_task' -Description 'IMU task must use static allocation'
Assert-Contains -Path $main -Pattern '#ifndef GRAY_VOFA_TELEMETRY_ENABLE' -Description 'Gray VOFA telemetry must remain build-configurable'
Assert-Contains -Path $main -Pattern '#define GRAY_VOFA_TELEMETRY_ENABLE 0U' -Description 'Gray VOFA telemetry must default to disabled'
Assert-Contains -Path $main -Pattern '#if GRAY_VOFA_TELEMETRY_ENABLE' -Description 'Gray VOFA output must be compile-time gated'
Assert-Contains -Path $main -Pattern 'GRAY_SAMPLE_INTERVAL_MS\s+10U' -Description 'Gray task must sample every 10 ms'
Assert-Contains -Path $main -Pattern 'GRAY_VOFA_TELEMETRY_INTERVAL_MS\s+100U' -Description 'Gray VOFA telemetry must run at 10 Hz'
Assert-Contains -Path $main -Pattern 'GRAY_VOFA_CHANNEL_COUNT\s+22U' -Description 'Gray VOFA telemetry must expose 22 channels'
Assert-Contains -Path $main -Pattern 'VOFA_JUSTFLOAT_FRAME_SIZE\(GRAY_VOFA_CHANNEL_COUNT\)' -Description 'Gray VOFA telemetry must allocate the 92-byte frame'
Assert-Contains -Path $main -Pattern 'g_grayscale_snapshot' -Description 'Application must retain grayscale samples for debugger observation'
Assert-Contains -Path $main -Pattern 'line_tracking_update' -Description 'Gray task must calculate line tracking observations'
Assert-Contains -Path $main -Pattern 'black_mask' -Description 'Application must publish the black-line mask'
Assert-Contains -Path $main -Pattern 'line_error' -Description 'Application must publish the analog line error'
Assert-Contains -Path $main -Pattern 'xTaskCreateStatic\(gray_task' -Description 'Gray task must use static allocation'
Assert-Contains -Path $main -Pattern 'board_imu_yaw_update' -Description 'IMU task must update the yaw estimator'
Assert-Contains -Path $main -Pattern 'vofa_justfloat_encode3' -Description 'IMU yaw telemetry must use JustFloat encoding'
Assert-Contains -Path $main -Pattern 'yaw_state\.yaw_deg.*yaw_state\.yaw_rate_dps.*yaw_state\.gyro_bias_z_dps' -Description 'IMU yaw JustFloat channels must be yaw, rate, then bias'
Assert-Contains -Path $main -Pattern 'board_uart_write\(frame, sizeof\(frame\)\)' -Description 'IMU yaw telemetry must send a complete JustFloat frame'
Assert-NotContains -Path $main -Pattern 'bmi160,id=0x|imu,ax=' -Description 'IMU telemetry must not emit text frames'
Assert-Contains -Path $imuYawHeader -Pattern 'board_imu_yaw_state_t' -Description 'Yaw driver must expose estimator state'
Assert-Contains -Path $imuYawHeader -Pattern 'BOARD_IMU_YAW_STARTUP_CALIBRATION_SAMPLES\s+100U' -Description 'Yaw driver must use a one-second startup calibration'
Assert-Contains -Path $imuYaw -Pattern '65\.6f' -Description 'Yaw driver must convert the ±500 dps gyro range'
Assert-Contains -Path $imuYaw -Pattern '8192\.0f' -Description 'Yaw driver must convert the ±4g accelerometer range'
Assert-Contains -Path $imuYaw -Pattern 'BOARD_IMU_YAW_GYRO_Z_SIGN\s+1\.0f' -Description 'Yaw driver must define the default positive Z yaw direction'
Assert-Contains -Path $imuYaw -Pattern 'BOARD_MOTOR_FRONT_LEFT' -Description 'Yaw driver must use front-left encoder speed'
Assert-Contains -Path $imuYaw -Pattern 'BOARD_MOTOR_REAR_LEFT' -Description 'Yaw driver must use rear-left encoder speed'
Assert-Contains -Path $imuYaw -Pattern 'BOARD_MOTOR_FRONT_RIGHT' -Description 'Yaw driver must use front-right encoder speed'
Assert-Contains -Path $imuYaw -Pattern 'BOARD_MOTOR_REAR_RIGHT' -Description 'Yaw driver must use rear-right encoder speed'
Assert-Contains -Path $imuYaw -Pattern 'BOARD_IMU_YAW_GYRO_WEIGHT\s+0\.98f' -Description 'Yaw fusion must prioritize the gyro'
Assert-Contains -Path $imuYaw -Pattern 'BOARD_IMU_YAW_ENCODER_WEIGHT\s+0\.02f' -Description 'Yaw fusion must use encoder aiding'
Assert-Contains -Path $imuYaw -Pattern 'normalize_yaw' -Description 'Yaw driver must normalize the signed yaw range'
    # Gray telemetry is binary JustFloat; legacy text output is forbidden.
Assert-Contains -Path $main -Pattern 'channels\[16U\].*snapshot\.digital' -Description 'Gray VOFA channel 16 must be digital'
Assert-Contains -Path $main -Pattern 'channels\[17U\].*snapshot\.black_mask' -Description 'Gray VOFA channel 17 must be black mask'
Assert-Contains -Path $main -Pattern 'channels\[18U\].*snapshot\.black_count' -Description 'Gray VOFA channel 18 must be black count'
Assert-Contains -Path $main -Pattern 'channels\[19U\].*snapshot\.line_error' -Description 'Gray VOFA channel 19 must be line error'
Assert-Contains -Path $main -Pattern 'channels\[20U\].*snapshot\.line_strength' -Description 'Gray VOFA channel 20 must be line strength'
Assert-Contains -Path $main -Pattern 'channels\[21U\].*snapshot\.sequence' -Description 'Gray VOFA channel 21 must be sequence'
Assert-Contains -Path $main -Pattern 'vofa_justfloat_encode\(frame' -Description 'Gray telemetry must encode a generic JustFloat frame'
Assert-Contains -Path $main -Pattern 'gray_vofa_task' -Description 'Application must provide a gray VOFA telemetry task'
Assert-NotContains -Path $main -Pattern 'continue;' -Description 'Telemetry snapshot retries must not compare an uninitialized sequence value'
Assert-Contains -Path $main -Pattern 'BUZZER_FEATURE_ENABLE\s+0U' -Description 'Buzzer feature must default to disabled'
Assert-Contains -Path $main -Pattern 'BUZZER_FREQUENCY_HZ\s+2000U' -Description 'Buzzer frequency must default to 2 kHz'
Assert-Contains -Path $main -Pattern 'BUZZER_DUTY_PERCENT\s+50U' -Description 'Buzzer duty cycle must default to 50 percent'
Assert-Contains -Path $main -Pattern 'BUZZER_ON_TIME_MS\s+200U' -Description 'Buzzer on time must default to 200 ms'
Assert-Contains -Path $main -Pattern 'BUZZER_OFF_TIME_MS\s+1800U' -Description 'Buzzer off time must default to 1800 ms'
Assert-Contains -Path $main -Pattern '#if BUZZER_FEATURE_ENABLE' -Description 'Buzzer task creation must be compile-time gated'
Assert-Contains -Path $main -Pattern 'xTaskCreateStatic\(buzzer_task' -Description 'Buzzer task must use static allocation'
Assert-Contains -Path $main -Pattern 'pdMS_TO_TICKS\(BUZZER_ON_TIME_MS\)' -Description 'Buzzer task must use configured on time'
Assert-Contains -Path $main -Pattern 'pdMS_TO_TICKS\(BUZZER_OFF_TIME_MS\)' -Description 'Buzzer task must use configured off time'
Assert-Contains -Path $main -Pattern 'BUTTON_TASK_STACK_DEPTH\s+128U' -Description 'Button task must use a 128-word static stack'
Assert-Contains -Path $main -Pattern 'BUTTON_TASK_INTERVAL_MS\s+10U' -Description 'Button task must scan every 10 ms'
Assert-Contains -Path $main -Pattern 'BUTTON_FEATURE_ENABLE\s+0U' -Description 'Button feature must default to disabled'
Assert-Contains -Path $main -Pattern '#if BUTTON_FEATURE_ENABLE' -Description 'Button feature must be compile-time gated'
Assert-OrderedPatterns -Path $main -Patterns @('#if BUTTON_FEATURE_ENABLE', 'static StaticTask_t g_button_task_buffer;', 'static StackType_t g_button_task_stack', '#endif') -Description 'Button task storage must be compile-time gated'
Assert-OrderedPatterns -Path $main -Patterns @('SYSCFG_DL_init\(\);', '#if BUTTON_FEATURE_ENABLE', 'board_buttons_init\(\);', '#endif') -Description 'Button initialization must be compile-time gated'
Assert-OrderedPatterns -Path $main -Patterns @('xTaskCreateStatic\(ws2812_task', '#if BUTTON_FEATURE_ENABLE', 'xTaskCreateStatic\(button_task', '#endif') -Description 'Button task creation must be compile-time gated'
Assert-Contains -Path $main -Pattern 'board_buttons_init' -Description 'Application must initialize the button driver'
Assert-Contains -Path $main -Pattern 'board_buttons_scan' -Description 'Button task must scan button states'
Assert-Contains -Path $main -Pattern 'xTaskCreateStatic\(button_task' -Description 'Button task must use static allocation'
Assert-Contains -Path $main -Pattern 'key,pa7=down\\r\\n' -Description 'Button task must report PA7 press events'
Assert-Contains -Path $main -Pattern 'key,pa7=up\\r\\n' -Description 'Button task must report PA7 release events'
Assert-Contains -Path $main -Pattern 'key,pb12=down\\r\\n' -Description 'Button task must report PB12 press events'
Assert-Contains -Path $main -Pattern 'key,pb12=up\\r\\n' -Description 'Button task must report PB12 release events'
Assert-Contains -Path $main -Pattern 'key,pa8=down\\r\\n' -Description 'Button task must report PA8 press events'
Assert-Contains -Path $main -Pattern 'key,pa8=up\\r\\n' -Description 'Button task must report PA8 release events'
Assert-Contains -Path $main -Pattern 'key,pa30=down\\r\\n' -Description 'Button task must report PA30 press events'
Assert-Contains -Path $main -Pattern 'key,pa30=up\\r\\n' -Description 'Button task must report PA30 release events'
Assert-Contains -Path $buttonsHeader -Pattern 'board_buttons_events_t' -Description 'Button driver must expose an event type'
Assert-Contains -Path $buttonsHeader -Pattern 'BOARD_BUTTON_PA7' -Description 'Button driver must expose PA7'
Assert-Contains -Path $buttonsHeader -Pattern 'BOARD_BUTTON_PB12' -Description 'Button driver must expose PB12'
Assert-Contains -Path $buttonsHeader -Pattern 'BOARD_BUTTON_PA8' -Description 'Button driver must expose PA8'
Assert-Contains -Path $buttonsHeader -Pattern 'BOARD_BUTTON_PA30' -Description 'Button driver must expose PA30'
Assert-Contains -Path $buttons -Pattern 'DL_GPIO_readPins' -Description 'Button driver must read GPIO input levels'
Assert-Contains -Path $buttons -Pattern '== 0U' -Description 'Button driver must treat low level as pressed'
Assert-Contains -Path $buttons -Pattern 'BUTTONS_BUTTON_PA7_PORT' -Description 'Button driver must use the generated PA7 port macro'
Assert-Contains -Path $buttons -Pattern 'BUTTONS_BUTTON_PB12_PORT' -Description 'Button driver must use the generated PB12 port macro'
Assert-Contains -Path $buttons -Pattern 'BUTTONS_BUTTON_PA8_PORT' -Description 'Button driver must use the generated PA8 port macro'
Assert-Contains -Path $buttons -Pattern 'BUTTONS_BUTTON_PA30_PORT' -Description 'Button driver must use the generated PA30 port macro'
Assert-Contains -Path $buttonsHeader -Pattern 'BOARD_BUTTON_DEBOUNCE_SAMPLES\s+2U' -Description 'Button driver must require two stable samples'
Assert-NotContains -Path $main -Pattern 'SysTick_Handler' -Description 'Application must not replace the FreeRTOS tick handler'
Assert-Contains -Path $buzzerHeader -Pattern 'board_buzzer_init' -Description 'Buzzer driver must expose initialization'
Assert-Contains -Path $buzzerHeader -Pattern 'board_buzzer_start' -Description 'Buzzer driver must expose start'
Assert-Contains -Path $buzzerHeader -Pattern 'board_buzzer_stop' -Description 'Buzzer driver must expose stop'
Assert-Contains -Path $buzzer -Pattern 'DL_Timer_setLoadValue' -Description 'Buzzer driver must set the PWM period'
Assert-Contains -Path $buzzer -Pattern 'DL_Timer_setCaptureCompareValue' -Description 'Buzzer driver must set the PWM duty cycle'
Assert-Contains -Path $buzzer -Pattern 'BUZZER_INST_CLK_FREQ' -Description 'Buzzer driver must use the generated timer clock frequency'
Assert-Contains -Path $buzzer -Pattern 'duty_percent > 100U' -Description 'Buzzer driver must clamp duty cycles above 100 percent'
Assert-Contains -Path $buzzer -Pattern 'frequency_hz < 1000U' -Description 'Buzzer driver must reject frequencies below 1 kHz'
Assert-Contains -Path $buzzer -Pattern 'frequency_hz > 20000U' -Description 'Buzzer driver must reject frequencies above 20 kHz'
Assert-Contains -Path $buzzer -Pattern 'BUZZER_INST' -Description 'Buzzer driver must use the generated PWM instance'
Assert-Contains -Path $bmi160Header -Pattern 'BOARD_BMI160_STATUS_CHIP_ID' -Description 'BMI160 driver must expose chip ID failures'
Assert-Contains -Path $bmi160Header -Pattern 'board_bmi160_init' -Description 'BMI160 driver must expose initialization'
Assert-Contains -Path $bmi160Header -Pattern 'board_bmi160_read_sample' -Description 'BMI160 driver must expose sample reads'
Assert-Contains -Path $bmi160 -Pattern 'DL_SPI_transmitData8' -Description 'BMI160 driver must transmit through SPI'
Assert-Contains -Path $bmi160 -Pattern 'DL_SPI_receiveData8' -Description 'BMI160 driver must receive through SPI'
Assert-Contains -Path $bmi160 -Pattern '0xD1U' -Description 'BMI160 driver must validate the expected chip ID'
Assert-Contains -Path $bmi160 -Pattern '0x7EU' -Description 'BMI160 driver must use the command register'
Assert-Contains -Path $bmi160 -Pattern '0xB6U' -Description 'BMI160 driver must issue the soft reset command'
Assert-Contains -Path $bmi160 -Pattern 'BMI160_SPI_COMM_TEST_REGISTER\s+0x7FU' -Description 'BMI160 driver must define the official post-reset SPI communication test register'
Assert-Contains -Path $bmi160 -Pattern '0xFFU' -Description 'BMI160 driver must issue the SPI interface-selection dummy transaction'
Assert-Contains -Path $bmi160 -Pattern 'select_spi_interface' -Description 'BMI160 driver must explicitly switch the device to SPI after power-up'
Assert-OrderedPatterns -Path $bmi160 -Patterns @('status = select_spi_interface\(\);', 'status = read_registers\(BMI160_CHIP_ID_REGISTER,') -Description 'BMI160 SPI interface selection must precede the chip ID read'
Assert-Contains -Path $bmi160 -Pattern 'BMI160_PMU_STATUS_REGISTER\s+0x03U' -Description 'BMI160 driver must read back the power-management status'
Assert-Contains -Path $bmi160 -Pattern 'BMI160_ERROR_REGISTER\s+0x02U' -Description 'BMI160 driver must read the official configuration error register'
Assert-Contains -Path $bmi160 -Pattern 'BMI160_ERROR_CODE_MASK\s+0x1EU' -Description 'BMI160 driver must use the complete official error-code field'
Assert-Contains -Path $bmi160 -Pattern 'BMI160_REGISTER_WRITE_DELAY_MS\s+1U' -Description 'BMI160 register writes must define the official 1 ms inter-write delay'
Assert-Contains -Path $bmi160 -Pattern 'BMI160_ACCEL_CONFIG_REGISTER\s+0x40U' -Description 'BMI160 driver must define the accelerometer configuration register'
Assert-Contains -Path $bmi160 -Pattern 'BMI160_ACCEL_RANGE_REGISTER\s+0x41U' -Description 'BMI160 driver must define the accelerometer range register'
Assert-Contains -Path $bmi160 -Pattern 'BMI160_GYRO_CONFIG_REGISTER\s+0x42U' -Description 'BMI160 driver must define the gyroscope configuration register'
Assert-Contains -Path $bmi160 -Pattern 'BMI160_GYRO_RANGE_REGISTER\s+0x43U' -Description 'BMI160 driver must define the gyroscope range register'
Assert-Contains -Path $bmi160 -Pattern 'BOARD_BMI160_STATUS_CONFIGURATION' -Description 'BMI160 driver must reject configuration readback mismatches'
Assert-Contains -Path $bmi160 -Pattern 'pmu_status' -Description 'BMI160 initialization must validate sensor power modes'
Assert-Contains -Path $bmi160 -Pattern '12U' -Description 'BMI160 driver must read twelve contiguous data bytes'
Assert-Contains -Path $bmi160 -Pattern 'BMI160_GYRO_DATA_REGISTER\s+0x0CU' -Description 'BMI160 contiguous sample read must start at the gyroscope data register'
Assert-Contains -Path $bmi160 -Pattern 'read_registers\(BMI160_GYRO_DATA_REGISTER, data, BMI160_DATA_LENGTH\)' -Description 'BMI160 sample read must fetch the gyro and accelerometer register block'
Assert-OrderedPatterns -Path $bmi160 -Patterns @('sample->gyro_x\s*=.*data\[1\]', 'sample->gyro_y\s*=.*data\[3\]', 'sample->gyro_z\s*=.*data\[5\]', 'sample->accel_x\s*=.*data\[7\]', 'sample->accel_y\s*=.*data\[9\]', 'sample->accel_z\s*=.*data\[11\]') -Description 'BMI160 sample parsing must match the gyro-first register block'
Assert-OrderedPatterns -Path $bmi160 -Patterns @('status = write_register\(BMI160_ACCEL_CONFIG_REGISTER,', 'status = write_register\(BMI160_ACCEL_RANGE_REGISTER,', 'status = write_register\(BMI160_GYRO_CONFIG_REGISTER,', 'status = write_register\(BMI160_GYRO_RANGE_REGISTER,', 'status = write_register\(BMI160_COMMAND_REGISTER, BMI160_ACCEL_NORMAL_COMMAND\)', 'status = write_register\(BMI160_COMMAND_REGISTER, BMI160_GYRO_NORMAL_COMMAND\)') -Description 'BMI160 initialization must configure registers before enabling normal power modes'
Assert-OrderedPatterns -Path $bmi160 -Patterns @('write_register\(BMI160_COMMAND_REGISTER, BMI160_SOFT_RESET_COMMAND\)', 'read_registers\(BMI160_SPI_COMM_TEST_REGISTER,', 'write_register\(BMI160_ACCEL_CONFIG_REGISTER,') -Description 'BMI160 must re-enable SPI after the soft reset before configuration writes'
Assert-Contains -Path $bmi160 -Pattern 'BOARD_BMI160_STATUS_TIMEOUT' -Description 'BMI160 driver must report bounded SPI timeouts'
Assert-Contains -Path $grayscaleHeader -Pattern 'board_grayscale_snapshot_t' -Description 'Grayscale driver must expose a snapshot type'
Assert-Contains -Path $grayscaleHeader -Pattern 'board_grayscale_init' -Description 'Grayscale driver must expose initialization'
Assert-Contains -Path $grayscaleHeader -Pattern 'board_grayscale_sample' -Description 'Grayscale driver must expose sampling'
Assert-Contains -Path $grayscaleHeader -Pattern 'BOARD_GRAYSCALE_CHANNEL_COUNT\s+8U' -Description 'Grayscale driver must define eight channels'
Assert-Contains -Path $grayscale -Pattern 'DL_ADC12_startConversion' -Description 'Grayscale driver must start ADC conversions'
Assert-Contains -Path $grayscale -Pattern 'DL_ADC12_initSingleSample' -Description 'Grayscale driver must initialize ADC single-sample mode'
Assert-Contains -Path $grayscale -Pattern 'DL_ADC12_REPEAT_MODE_DISABLED' -Description 'Grayscale ADC must use a bounded single conversion'
Assert-Contains -Path $grayscale -Pattern 'DL_ADC12_TRIG_SRC_SOFTWARE' -Description 'Grayscale ADC must use software conversion triggers'
Assert-Contains -Path $grayscale -Pattern 'DL_ADC12_SAMP_CONV_RES_12_BIT' -Description 'Grayscale ADC must use 12-bit conversion resolution'
Assert-Contains -Path $grayscale -Pattern 'DL_ADC12_getRawInterruptStatus' -Description 'Grayscale driver must wait for the ADC result flag'
Assert-Contains -Path $grayscale -Pattern 'DL_ADC12_clearInterruptStatus' -Description 'Grayscale driver must clear the ADC result flag'
Assert-Contains -Path $grayscale -Pattern 'GRAYSCALE_ADC_WAIT_LIMIT\s+100000U' -Description 'Grayscale ADC wait must be bounded'
Assert-Contains -Path $grayscale -Pattern 'g_grayscale_adc_timeout_count' -Description 'Grayscale driver must expose ADC timeout diagnostics'
Assert-Contains -Path $grayscale -Pattern 'DL_ADC12_getMemResult' -Description 'Grayscale driver must read ADC results'
Assert-Contains -Path $grayscale -Pattern 'GRAYSCALE_ADC_SAMPLES_PER_CHANNEL\s+8U' -Description 'Grayscale driver must average eight ADC samples'
Assert-Contains -Path $grayscale -Pattern 'DL_Common_delayCycles' -Description 'Grayscale driver must wait after address changes'
Assert-Contains -Path $grayscale -Pattern 'PB13' -Description 'Grayscale driver must document AD0 on PB13'
Assert-Contains -Path $grayscale -Pattern 'PB1' -Description 'Grayscale driver must document AD1 on PB1'
Assert-Contains -Path $grayscale -Pattern 'PB23' -Description 'Grayscale driver must document AD2 on PB23'
Assert-Contains -Path $grayscale -Pattern '4095U' -Description 'Grayscale driver must use 12-bit normalization'
Assert-Contains -Path $grayscale -Pattern 'Gray.*white|gray_white' -Description 'Grayscale driver must implement gray-white hysteresis threshold'
Assert-Contains -Path $grayscale -Pattern 'Gray.*black|gray_black' -Description 'Grayscale driver must implement gray-black hysteresis threshold'
Assert-Contains -Path $grayscale -Pattern 'white\s*<=\s*black' -Description 'Grayscale driver must reject equal or reversed calibration ranges'
Assert-Contains -Path $grayscaleHeader -Pattern 'black_mask' -Description 'Grayscale snapshot must expose the black-line mask'
Assert-Contains -Path $grayscaleHeader -Pattern 'black_count' -Description 'Grayscale snapshot must expose the black-line count'
Assert-Contains -Path $grayscaleHeader -Pattern 'line_strength' -Description 'Grayscale snapshot must expose total black-line strength'
Assert-Contains -Path $grayscaleHeader -Pattern 'line_error' -Description 'Grayscale snapshot must expose the analog line error'
Assert-Contains -Path $lineTrackingHeader -Pattern 'line_tracking_state_t' -Description 'Line tracking must expose static state'
Assert-Contains -Path $lineTrackingHeader -Pattern 'line_tracking_update' -Description 'Line tracking must expose its update API'
Assert-Contains -Path $lineTracking -Pattern 'BOARD_GRAYSCALE_ADC_MAX\s*-\s*normalized' -Description 'Line tracking must derive blackness from normalized values'
Assert-Contains -Path $lineTracking -Pattern '-3500.*-2500.*-1500.*-500' -Description 'Line tracking must define signed channel weights'
Assert-Contains -Path $buildScript -Pattern 'line_tracking\.c' -Description 'CCS build must compile line tracking'
Assert-Contains -Path $motorHeader -Pattern 'BOARD_MOTOR_DIRECTION_STOP' -Description 'Motor driver must expose a stop direction'
Assert-Contains -Path $motorHeader -Pattern 'BOARD_MOTOR_DIRECTION_FORWARD' -Description 'Motor driver must expose a forward direction'
Assert-Contains -Path $motorHeader -Pattern 'BOARD_MOTOR_DIRECTION_REVERSE' -Description 'Motor driver must expose a reverse direction'
Assert-Contains -Path $motorHeader -Pattern 'board_motor_set_signed_duty' -Description 'Motor driver must expose signed duty output'
Assert-Contains -Path $motor -Pattern 'duty_percent > 100U' -Description 'Motor driver must clamp duty cycles above 100 percent'
Assert-Contains -Path $motor -Pattern 'DL_Timer_setCaptureCompareValue' -Description 'Motor driver must update PWM compare values'
Assert-Contains -Path $motor -Pattern 'BOARD_MOTOR_DIRECTION_FORWARD' -Description 'Motor driver must drive IN1 for forward motion'
Assert-Contains -Path $motor -Pattern 'BOARD_MOTOR_DIRECTION_REVERSE' -Description 'Motor driver must drive IN2 for reverse motion'
Assert-Contains -Path $motor -Pattern 'board_motor_set_signed_duty' -Description 'Motor driver must map signed duty to direction and PWM'
Assert-OrderedPatterns -Path $motor -Patterns @('case BOARD_MOTOR_FRONT_LEFT:', 'MOTOR_FRONT_LEFT_INST') -Description 'Logical front-left wheel must use its matching PWM instance'
Assert-OrderedPatterns -Path $motor -Patterns @('case BOARD_MOTOR_FRONT_RIGHT:', 'MOTOR_FRONT_RIGHT_INST') -Description 'Logical front-right wheel must use its matching PWM instance'
Assert-OrderedPatterns -Path $motor -Patterns @('case BOARD_MOTOR_REAR_LEFT:', 'BOARD_MOTOR_DIRECTION_REVERSE', 'MOTOR_REAR_LEFT_INST') -Description 'Logical rear-left wheel must invert direction through its matching PWM instance'
Assert-OrderedPatterns -Path $motor -Patterns @('case BOARD_MOTOR_REAR_RIGHT:', 'MOTOR_REAR_RIGHT_INST') -Description 'Logical rear-right wheel must use its matching PWM instance'
Assert-Contains -Path $uart -Pattern 'xQueueSendFromISR' -Description 'UART ISR must queue received bytes'
Assert-Contains -Path $uart -Pattern 'DL_UART_Main_isRXFIFOEmpty' -Description 'UART ISR must drain the receive FIFO'
Assert-Contains -Path $uart -Pattern 'NVIC_SetPriority' -Description 'UART ISR priority must be compatible with FreeRTOS FromISR APIs'
Assert-Contains -Path $uart -Pattern 'board_uart_write' -Description 'UART driver must provide a frame write interface'
Assert-Contains -Path $uart -Pattern 'xQueueCreateStatic' -Description 'UART writer must use a static transmit queue'
Assert-Contains -Path $uart -Pattern 'xQueueSend' -Description 'UART frame writes must enqueue whole messages'
Assert-Contains -Path $uart -Pattern 'xQueueReceive' -Description 'Dedicated UART transmit task must dequeue messages'
Assert-Contains -Path $uart -Pattern 'board_uart_tx_task' -Description 'UART driver must provide the dedicated transmit task'
Assert-Contains -Path $encoderHeader -Pattern 'board_encoder_sample_t' -Description 'Encoder driver must expose a sample type'
Assert-Contains -Path $encoderHeader -Pattern 'delta_counts' -Description 'Encoder samples must expose interval counts'
Assert-Contains -Path $encoderHeader -Pattern 'total_counts' -Description 'Encoder samples must expose accumulated counts'
Assert-Contains -Path $encoderHeader -Pattern 'speed_mm_per_s' -Description 'Encoder samples must expose wheel speed'
Assert-Contains -Path $encoderHeader -Pattern 'BOARD_ENCODER_MOTOR_LINES_PER_REVOLUTION\s+13U' -Description 'Encoder driver must expose the 13-line motor encoder configuration'
Assert-Contains -Path $encoderHeader -Pattern 'BOARD_ENCODER_GEAR_RATIO\s+20U' -Description 'Encoder driver must expose the 20:1 gearbox configuration'
Assert-Contains -Path $encoderHeader -Pattern 'BOARD_ENCODER_OUTPUT_SHAFT_LINES_PER_REVOLUTION' -Description 'Encoder driver must derive output shaft lines from mechanics'
Assert-Contains -Path $encoderHeader -Pattern 'BOARD_ENCODER_DECODE_MODE_A_PHASE_DUAL_EDGE' -Description 'Encoder driver must expose the A-phase dual-edge decode mode'
Assert-Contains -Path $encoderHeader -Pattern 'BOARD_ENCODER_DECODE_MODE_AB_PHASE_QUADRATURE_X4' -Description 'Encoder driver must expose the AB quadrature X4 decode mode'
Assert-Contains -Path $encoderHeader -Pattern 'BOARD_ENCODER_COUNTS_PER_REVOLUTION' -Description 'Encoder driver must derive counts per revolution from mechanics and decode mode'
Assert-Contains -Path $encoderHeader -Pattern 'BOARD_ENCODER_WHEEL_DIAMETER_MM\s+48' -Description 'Encoder driver must define the reference wheel diameter'
Assert-Contains -Path $motorControlHeader -Pattern 'g_motor_speed_targets_mm_s' -Description 'Motor control must expose SWD four-wheel speed targets'
Assert-Contains -Path $motorControlHeader -Pattern 'g_motor_debug' -Description 'Motor control must expose the SWD debug state'
Assert-Contains -Path $motorControlHeader -Pattern 'MOTOR_CONTROL_DEBUG_MODE_PWM' -Description 'Motor control must expose PWM debug mode'
Assert-Contains -Path $motorControlHeader -Pattern 'MOTOR_CONTROL_DEBUG_MODE_SPEED' -Description 'Motor control must expose speed debug mode'
Assert-Contains -Path $motorControl -Pattern 'PID_Incremental_Calc' -Description 'Motor control must run the incremental speed PID'
Assert-Contains -Path $motorControl -Pattern 'PID_Position_Init' -Description 'Motor control must retain the position PID state'
Assert-Contains -Path $motorControl -Pattern 'MOTOR_CONTROL_MAX_DUTY_PERCENT\s+100\.0f' -Description 'Motor control must clamp output to signed 100 percent PWM'
Assert-Contains -Path $motorPidHeader -Pattern 'PID_Position_Calc' -Description 'PID core must provide position PID'
Assert-Contains -Path $motorPidHeader -Pattern 'PID_Incremental_Calc' -Description 'PID core must provide incremental PID'
Assert-Contains -Path $encoder -Pattern 'DL_GPIO_getPendingInterrupt\(GPIOA\)' -Description 'Encoder driver must dispatch GPIOA edge interrupts'
Assert-Contains -Path $encoder -Pattern 'DL_GPIO_readPins' -Description 'Encoder driver must read B phases to determine direction'
Assert-Contains -Path $encoder -Pattern 'RISE_FALL' -Description 'Encoder source must document A-phase dual-edge handling'
Assert-Contains -Path $encoder -Pattern 'board_encoder_quadrature_update' -Description 'Encoder driver must use a quadrature state decoder for X4 mode'
Assert-Contains -Path $encoder -Pattern 'DL_GPIO_disableInterrupt' -Description 'Default A-phase mode must disable optional B-edge interrupts'
Assert-Contains -Path $main -Pattern 'DL_Interrupt_getPendingGroup' -Description 'Application must dispatch shared GPIOA and GPIOB group interrupts'
Assert-Contains -Path $encoder -Pattern 'ENCODER_FRONT_LEFT_A_IIDX' -Description 'Encoder driver must use generated front-left A interrupt definitions'
Assert-Contains -Path $encoder -Pattern 'ENCODER_FRONT_RIGHT_A_IIDX' -Description 'Encoder driver must use generated front-right A interrupt definitions'
Assert-Contains -Path $encoder -Pattern 'ENCODER_REAR_LEFT_A_IIDX' -Description 'Encoder driver must use generated rear-left A interrupt definitions'
Assert-Contains -Path $encoder -Pattern 'ENCODER_REAR_RIGHT_A_IIDX' -Description 'Encoder driver must use generated rear-right A interrupt definitions'
Assert-OrderedPatterns -Path $encoder -Patterns @(
    'case ENCODER_FRONT_LEFT_A_IIDX:',
    'BOARD_MOTOR_FRONT_LEFT',
    '\s*,\s*1\);',
    'case ENCODER_FRONT_RIGHT_A_IIDX:',
    'BOARD_MOTOR_FRONT_RIGHT',
    '\s*,\s*-1\);',
    'case ENCODER_REAR_LEFT_A_IIDX:',
    'BOARD_MOTOR_REAR_LEFT',
    '\s*,\s*1\);',
    'case ENCODER_REAR_RIGHT_A_IIDX:',
    'BOARD_MOTOR_REAR_RIGHT',
    '\s*,\s*-1\);'
) -Description 'Encoder GPIO channels must match the measured physical wheel mapping and direction signs'
Assert-Contains -Path $syscfg -Pattern 'PB22' -Description 'WS2812 data output must use PB22'
Assert-Contains -Path $syscfg -Pattern 'HSCLKMUX.*SYSPLL0' -Description 'Application CPU clock must use SYSPLL0'
Assert-Contains -Path $syscfg -Pattern 'HFXT' -Description 'Application SYSPLL reference must use the HFXT'
Assert-Contains -Path $syscfg -Pattern 'inputFreq\s*=\s*40' -Description 'Application HFXT frequency must be 40 MHz'
Assert-Contains -Path $syscfg -Pattern 'pllQDiv\.multiplyValue\s*=\s*5' -Description 'Application SYSPLL multiplier must produce an 80 MHz CPU clock'
Assert-Contains -Path $syscfg -Pattern 'ulpDiv\.divideValue\s*=\s*2' -Description 'Application ULPCLK must divide the 80 MHz CPU clock by two'
Assert-Contains -Path $rtosConfig -Pattern 'configCPU_CLOCK_HZ\s+\(80000000UL\)' -Description 'FreeRTOS CPU clock must match the 80 MHz SysConfig clock'
Assert-Contains -Path $syscfg -Pattern 'PA10' -Description 'UART0 TX must remain on PA10'
Assert-Contains -Path $syscfg -Pattern 'PA11' -Description 'UART0 RX must remain on PA11'
Assert-Contains -Path $syscfg -Pattern 'enableFIFO\s*=\s*true' -Description 'UART0 receive FIFO must be enabled'
Assert-Contains -Path $syscfg -Pattern 'ENCODER' -Description 'SysConfig must define the encoder input group'
Assert-Contains -Path $syscfg -Pattern 'PA16' -Description 'Front-left encoder A phase must use PA16'
Assert-Contains -Path $syscfg -Pattern 'PB20' -Description 'Front-left encoder B phase must use PB20'
Assert-Contains -Path $syscfg -Pattern 'PA14' -Description 'Front-right encoder A phase must use PA14'
Assert-Contains -Path $syscfg -Pattern 'PA9' -Description 'Front-right encoder B phase must use PA9'
Assert-Contains -Path $syscfg -Pattern 'PA15' -Description 'Rear-left encoder A phase must use PA15'
Assert-Contains -Path $syscfg -Pattern 'PB24' -Description 'Rear-left encoder B phase must use PB24'
Assert-Contains -Path $syscfg -Pattern 'PA17' -Description 'Rear-right encoder A phase must use PA17'
Assert-Contains -Path $syscfg -Pattern 'PA22' -Description 'Rear-right encoder B phase must use PA22'
Assert-Contains -Path $syscfg -Pattern 'RISE_FALL' -Description 'Encoder A phases must interrupt on both edges'
Assert-Contains -Path $syscfg -Pattern 'PULL_UP' -Description 'Encoder inputs must use pull-ups'
Assert-OrderedPatterns -Path $syscfg -Patterns @('FRONT_LEFT_A', 'interruptEn\s*=\s*true', 'polarity\s*=\s*"RISE_FALL"', 'PA15') -Description 'Front-left A must use PA15 dual-edge interrupts'
Assert-OrderedPatterns -Path $syscfg -Patterns @('FRONT_LEFT_B', 'PULL_UP', 'PB24') -Description 'Front-left B must use PB24 pull-up input'
Assert-OrderedPatterns -Path $syscfg -Patterns @('FRONT_RIGHT_A', 'interruptEn\s*=\s*true', 'polarity\s*=\s*"RISE_FALL"', 'PA17') -Description 'Front-right A must use PA17 dual-edge interrupts'
Assert-OrderedPatterns -Path $syscfg -Patterns @('FRONT_RIGHT_B', 'PULL_UP', 'PA22') -Description 'Front-right B must use PA22 pull-up input'
Assert-OrderedPatterns -Path $syscfg -Patterns @('REAR_LEFT_A', 'interruptEn\s*=\s*true', 'polarity\s*=\s*"RISE_FALL"', 'PA14') -Description 'Rear-left A must use PA14 dual-edge interrupts'
Assert-OrderedPatterns -Path $syscfg -Patterns @('REAR_LEFT_B', 'PULL_UP', 'PA9') -Description 'Rear-left B must use PA9 pull-up input'
Assert-OrderedPatterns -Path $syscfg -Patterns @('REAR_RIGHT_A', 'interruptEn\s*=\s*true', 'polarity\s*=\s*"RISE_FALL"', 'PA16') -Description 'Rear-right A must use PA16 dual-edge interrupts'
Assert-OrderedPatterns -Path $syscfg -Patterns @('REAR_RIGHT_B', 'PULL_UP', 'PB20') -Description 'Rear-right B must use PB20 pull-up input'
Assert-OrderedPatterns -Path $syscfg -Patterns @('REAR_RIGHT_B', 'interruptEn\s*=\s*true', 'polarity\s*=\s*"RISE_FALL"', 'PB20') -Description 'Rear-right B must provide dual-edge interrupts for X4 mode'
Assert-OrderedPatterns -Path $syscfg -Patterns @('REAR_LEFT_B', 'interruptEn\s*=\s*true', 'polarity\s*=\s*"RISE_FALL"', 'PA9') -Description 'Rear-left B must provide dual-edge interrupts for X4 mode'
Assert-OrderedPatterns -Path $syscfg -Patterns @('FRONT_LEFT_B', 'interruptEn\s*=\s*true', 'polarity\s*=\s*"RISE_FALL"', 'PB24') -Description 'Front-left B must provide dual-edge interrupts for X4 mode'
Assert-OrderedPatterns -Path $syscfg -Patterns @('FRONT_RIGHT_B', 'interruptEn\s*=\s*true', 'polarity\s*=\s*"RISE_FALL"', 'PA22') -Description 'Front-right B must provide dual-edge interrupts for X4 mode'
Assert-Contains -Path $syscfg -Pattern 'MOTOR_FRONT_LEFT' -Description 'SysConfig must define the front-left motor PWM'
Assert-Contains -Path $syscfg -Pattern 'MOTOR_FRONT_RIGHT' -Description 'SysConfig must define the front-right motor PWM'
Assert-Contains -Path $syscfg -Pattern 'MOTOR_REAR_LEFT' -Description 'SysConfig must define the rear-left motor PWM'
Assert-Contains -Path $syscfg -Pattern 'MOTOR_REAR_RIGHT' -Description 'SysConfig must define the rear-right motor PWM'
Assert-Contains -Path $syscfg -Pattern 'PA12' -Description 'Front-left motor IN1 must use PA12'
Assert-Contains -Path $syscfg -Pattern 'PA13' -Description 'Front-left motor IN2 must use PA13'
Assert-Contains -Path $syscfg -Pattern 'PA28' -Description 'Front-right motor IN1 must use PA28'
Assert-Contains -Path $syscfg -Pattern 'PA31' -Description 'Front-right motor IN2 must use PA31'
Assert-Contains -Path $syscfg -Pattern 'PA29' -Description 'Rear-left motor IN1 must use PA29'
Assert-Contains -Path $syscfg -Pattern 'PB27' -Description 'Rear-left motor IN2 must use PB27'
Assert-Contains -Path $syscfg -Pattern 'PB4' -Description 'Rear-right motor IN1 must use PB4'
Assert-Contains -Path $syscfg -Pattern 'PB5' -Description 'Rear-right motor IN2 must use PB5'
Assert-Contains -Path $syscfg -Pattern 'timerCount\s*=\s*4000' -Description 'Motor PWM must use a 4000-tick period at its 40 MHz timer clock'
Assert-Contains -Path $syscfg -Pattern 'PWMFrontLeft\.clockPrescale\s*=\s*2' -Description 'Front-left motor timer must prescale 80 MHz to 40 MHz'
Assert-Contains -Path $syscfg -Pattern 'PWMFrontRight\.clockDivider\s*=\s*2' -Description 'Front-right motor timer must divide 80 MHz to 40 MHz'
Assert-Contains -Path $syscfg -Pattern 'PWMRearLeft\.clockDivider\s*=\s*2' -Description 'Rear-left motor timer must divide 80 MHz to 40 MHz'
Assert-Contains -Path $syscfg -Pattern 'BUZZER' -Description 'SysConfig must define the buzzer PWM'
Assert-Contains -Path $syscfg -Pattern 'TIMG8' -Description 'Buzzer must use the dedicated TIMG8 peripheral'
Assert-Contains -Path $syscfg -Pattern 'ccp1Pin\.\$assign\s*=\s*"PA2"' -Description 'Buzzer PWM output must use PA2 CCP1'
Assert-Contains -Path $syscfg -Pattern 'PWMBuzzer\.timerCount\s*=\s*20000' -Description 'Buzzer timer must use the 2 kHz default period'
Assert-Contains -Path $ws2812Header -Pattern 'BOARD_WS2812_PIXEL_COUNT\s+4U' -Description 'WS2812 driver must target exactly four pixels'
Assert-Contains -Path $ws2812 -Pattern 'taskDISABLE_INTERRUPTS' -Description 'WS2812 frame writes must mask interrupts'
Assert-Contains -Path $ws2812 -Pattern 'taskENABLE_INTERRUPTS' -Description 'WS2812 frame writes must restore interrupts'
Assert-Contains -Path $ws2812 -Pattern 'WS2812_SPI_FRAME_BYTES\s+60U' -Description 'WS2812 SPI frame must include data and reset-low bytes'
Assert-Contains -Path $ws2812 -Pattern 'DL_SPI_transmitData8' -Description 'WS2812 driver must transmit encoded bytes through SPI'
Assert-Contains -Path $ws2812 -Pattern 'DL_SPI_isBusy' -Description 'WS2812 driver must wait for the SPI shifter to finish'
Assert-Contains -Path $ws2812 -Pattern '0x04U' -Description 'WS2812 zero bits must encode as SPI 100'
Assert-Contains -Path $ws2812 -Pattern '0x06U' -Description 'WS2812 one bits must encode as SPI 110'
Assert-OrderedPatterns -Path $ws2812 -Patterns @('send_byte\(pixel->green,', 'send_byte\(pixel->red,', 'send_byte\(pixel->blue,') -Description 'WS2812 bytes must be sent in GRB order'
Assert-Contains -Path $syscfg -Pattern 'SPI1\.targetBitRate\s*=\s*2666667' -Description 'SPI1 must clock WS2812 symbols at 2.666667 MHz'
Assert-Contains -Path $syscfg -Pattern 'SPI1\.peripheral\.mosiPin\.\$assign\s*=\s*"PB22"' -Description 'SPI1 PICO must use PB22'
Assert-Contains -Path $syscfg -Pattern 'SPI_BMI160' -Description 'SysConfig must define the BMI160 SPI instance'
Assert-Contains -Path $syscfg -Pattern 'SPI2\.targetBitRate\s*=\s*8000000' -Description 'BMI160 SPI must use an 8 MHz clock'
Assert-Contains -Path $syscfg -Pattern 'SPI2\.polarity\s*=\s*"1"' -Description 'BMI160 SPI must use active-high clock polarity for mode 3'
Assert-Contains -Path $syscfg -Pattern 'SPI2\.phase\s*=\s*"1"' -Description 'BMI160 SPI must use Motorola mode 3'
Assert-Contains -Path $syscfg -Pattern 'SPI2\.peripheral\.\$assign\s*=\s*"SPI0"' -Description 'BMI160 must use SPI0'
Assert-Contains -Path $syscfg -Pattern 'SPI2\.peripheral\.sclkPin\.\$assign\s*=\s*"PB18"' -Description 'BMI160 SPI clock must use PB18'
Assert-Contains -Path $syscfg -Pattern 'SPI2\.peripheral\.mosiPin\.\$assign\s*=\s*"PB17"' -Description 'BMI160 SPI MOSI must use PB17'
Assert-Contains -Path $syscfg -Pattern 'SPI2\.peripheral\.misoPin\.\$assign\s*=\s*"PB19"' -Description 'BMI160 SPI MISO must use PB19'
Assert-Contains -Path $syscfg -Pattern 'ADCGray\.repeatMode\s*=\s*false' -Description 'Grayscale ADC must use single conversions for bounded synchronous reads'
Assert-Contains -Path $syscfg -Pattern 'BMI160_CS' -Description 'SysConfig must define the BMI160 chip select GPIO'
Assert-Contains -Path $syscfg -Pattern 'initialValue\s*=\s*"SET"' -Description 'BMI160 chip select must idle high'
Assert-Contains -Path $syscfg -Pattern 'pin\.\$assign\s*=\s*"PB0"' -Description 'BMI160 chip select must use PB0'
Assert-Contains -Path $syscfg -Pattern 'BUTTONS' -Description 'SysConfig must define the button GPIO group'
Assert-OrderedPatterns -Path $syscfg -Patterns @('BUTTON_PA7', 'direction\s*=\s*"INPUT"', 'PA7') -Description 'PA7 button must be an input'
Assert-OrderedPatterns -Path $syscfg -Patterns @('BUTTON_PB12', 'direction\s*=\s*"INPUT"', 'PB12') -Description 'PB12 button must be an input'
Assert-OrderedPatterns -Path $syscfg -Patterns @('BUTTON_PA8', 'direction\s*=\s*"INPUT"', 'PA8') -Description 'PA8 button must be an input'
Assert-OrderedPatterns -Path $syscfg -Patterns @('BUTTON_PA30', 'direction\s*=\s*"INPUT"', 'PA30') -Description 'PA30 button must be an input'
Assert-NotContains -Path $syscfg -Pattern 'BUTTON_.*interruptEn' -Description 'Buttons must not use GPIO interrupts'
Assert-NotContains -Path $syscfg -Pattern 'BUTTON_.*internalResistor' -Description 'Buttons must rely on external pull-ups'
Assert-Contains -Path $buildScript -Pattern 'mspm0g3507_app\.out' -Description 'Build must link the app ELF'
Assert-Contains -Path $buildScript -Pattern 'board_ws2812\.c' -Description 'Build must compile the WS2812 driver'
Assert-Contains -Path $buildScript -Pattern 'board_motor\.c' -Description 'Build must compile the motor driver'
Assert-Contains -Path $buildScript -Pattern 'board_encoder\.c' -Description 'Build must compile the encoder driver'
Assert-Contains -Path $buildScript -Pattern 'board_buzzer\.c' -Description 'Build must compile the buzzer driver'
Assert-Contains -Path $buildScript -Pattern 'board_bmi160\.c' -Description 'Build must compile the BMI160 driver'
Assert-Contains -Path $buildScript -Pattern 'board_buttons\.c' -Description 'Build must compile the button driver'
Assert-Contains -Path $buildScript -Pattern 'board_grayscale\.c' -Description 'Build must compile the grayscale driver'
Assert-Contains -Path $buildScript -Pattern 'motor_control\.c' -Description 'Build must compile the motor control layer'
Assert-Contains -Path $buildScript -Pattern 'motor_pid\\pid\.c' -Description 'Build must compile the PID core'
Assert-Contains -Path $buildScript -Pattern 'vofa_justfloat\.c' -Description 'Build must compile the JustFloat encoder'
Assert-Contains -Path $buildScript -Pattern 'VofaSpeedPidTelemetryEnable' -Description 'Build must support compiling the VOFA telemetry path'
Assert-Contains -Path $buildScript -Pattern "PSBoundParameters\.ContainsKey\('VofaSpeedPidTelemetryEnable'\)" -Description 'Build must not override the source VOFA switch unless explicitly requested'
Assert-Contains -Path $buildScript -Pattern 'GrayVofaTelemetryEnable' -Description 'Build must support compiling the gray VOFA telemetry path'
Assert-Contains -Path $buildScript -Pattern "PSBoundParameters\.ContainsKey\('GrayVofaTelemetryEnable'\)" -Description 'Build must not override the source gray VOFA switch unless explicitly requested'
Assert-Contains -Path $vofaJustFloatHeader -Pattern 'VOFA_JUSTFLOAT_FRAME_SIZE' -Description 'JustFloat header must expose the fixed frame size'
Assert-Contains -Path $vofaJustFloatHeader -Pattern 'vofa_justfloat_encode\(' -Description 'JustFloat header must expose generic encoding'
Assert-Contains -Path $vofaJustFloat -Pattern 'channel_count == 0U' -Description 'JustFloat encoder must reject zero channels'
Assert-Contains -Path $vofaJustFloat -Pattern 'channels == NULL' -Description 'JustFloat encoder must reject null channel arrays'
Assert-Contains -Path $vofaJustFloat -Pattern '0x80U' -Description 'JustFloat encoder must append the VOFA frame tail'
Assert-Contains -Path $vofaJustFloat -Pattern '0x7FU' -Description 'JustFloat encoder must append the VOFA frame tail'
Assert-Contains -Path $buildScript -Pattern 'board_imu_yaw\.c' -Description 'Build must compile the IMU yaw driver'
Assert-Contains -Path $buildScript -Pattern 'ImuTelemetryEnable' -Description 'Build must support an explicit IMU telemetry override'
Assert-Contains -Path $buildScript -Pattern 'ImuYawEnable' -Description 'Build must support an explicit IMU yaw override'
Assert-Contains -Path $buildScript -Pattern "PSBoundParameters\.ContainsKey\('ImuTelemetryEnable'\)" -Description 'Build must only override IMU telemetry when requested'
Assert-Contains -Path $buildScript -Pattern "PSBoundParameters\.ContainsKey\('ImuYawEnable'\)" -Description 'Build must only override IMU yaw when requested'
Assert-Contains -Path $flashScript -Pattern "'app'" -Description 'Flash script must select the app ELF explicitly'
Assert-Contains -Path $tasks -Pattern 'MSPM0G3507 App: Build' -Description 'VS Code must provide an app build task'
Assert-Contains -Path $openKeilScript -Pattern 'ProjectRoot' -Description 'Keil opener must accept the project root'
Assert-Contains -Path $openKeilScript -Pattern 'KeilRoot' -Description 'Keil opener must accept the Keil root'
Assert-Contains -Path $openKeilScript -Pattern 'UV4\.exe' -Description 'Keil opener must locate UV4.exe'
Assert-Contains -Path $openKeilScript -Pattern 'mspm0g3507_app\.uvprojx' -Description 'Keil opener must locate the G3507 app project'
Assert-Contains -Path $openKeilScript -Pattern 'Test-Path' -Description 'Keil opener must validate required paths'
Assert-Contains -Path $openKeilScript -Pattern 'Start-Process' -Description 'Keil opener must launch UV4'
Assert-Contains -Path $tasks -Pattern 'MSPM0G3507 App: Open Keil Project' -Description 'VS Code must provide a Keil project opener task'
Assert-Contains -Path $tasks -Pattern 'open-keil-mspm0g3507-app\.ps1' -Description 'Keil opener task must call the dedicated script'
Assert-Contains -Path $tasks -Pattern '\$\{workspaceFolder\}' -Description 'Keil opener task must pass the workspace root'
Assert-NotContains -Path $openKeilScript -Pattern 'flash-and-debug|build-keil| -Action\s+Load' -Description 'Keil opener must not flash or build firmware'
Assert-Contains -Path $launch -Pattern 'MSPM0G3507 App: Attach to pyOCD' -Description 'VS Code must provide an app attach configuration'
Assert-Contains -Path $gitIgnore -Pattern '/mspm0g3507_app/Debug/' -Description 'App Debug output must be ignored'

Write-Host 'PASS: MSPM0G3507 app static integration checks passed.'
