#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_VOFA_HEALTH_TELEMETRY_ENABLE 0U
#define APP_VOFA_HEALTH_TELEMETRY_INTERVAL_MS 20U

/* JY901S 通过 UART8 输出 VOFA+ JustFloat 遥测；UART8 遥测模式只能同时启用一种。 */
#define APP_JY901S_VOFA_TELEMETRY_ENABLE 0U
#define APP_JY901S_VOFA_TELEMETRY_INTERVAL_MS 5U
#define APP_JY901S_TASK_PERIOD_MS 5U

/* 设为 1 时，VOFA 输出车体坐标和校准后的数据；设为 0 时保留传感器原始坐标输出。 */
#define APP_JY901S_VOFA_CALIBRATED_ENABLE 1U

/* 启动时自动估计陀螺仪零偏；结果只保存在 RAM，重启后重新采集。 */
#define APP_JY901S_CALIBRATION_ENABLE 1U
/* 连续满足静止条件的完整样本数量；车辆需保持静止约 2~3 秒。 */
#define APP_JY901S_CALIBRATION_SAMPLE_TARGET 200U
/* 从开始校准到失败的最大时间，单位 ms。 */
#define APP_JY901S_CALIBRATION_TIMEOUT_MS 5000U
/* 静止判断的加速度模长范围，单位 g。 */
#define APP_JY901S_CALIBRATION_STATIONARY_ACCEL_MIN_G 0.85f
#define APP_JY901S_CALIBRATION_STATIONARY_ACCEL_MAX_G 1.15f
/* 静止判断的单轴角速度最大值，单位 deg/s。 */
#define APP_JY901S_CALIBRATION_STATIONARY_GYRO_MAX_DPS 3.0f

/* 车体右手坐标系：X 向车头，Y 向车体左侧，Z 向上。 */
/* 每个车体轴对应的 JY901S 传感器轴：0=X，1=Y，2=Z；三个值必须互不相同。 */
#define APP_JY901S_VEHICLE_X_SENSOR_AXIS 1U
#define APP_JY901S_VEHICLE_Y_SENSOR_AXIS 0U
#define APP_JY901S_VEHICLE_Z_SENSOR_AXIS 2U
/* 对应轴的方向符号，只能为 1 或 -1；用于适配旋转、翻面等正交安装方向。 */
#define APP_JY901S_VEHICLE_X_SENSOR_SIGN 1
#define APP_JY901S_VEHICLE_Y_SENSOR_SIGN -1
#define APP_JY901S_VEHICLE_Z_SENSOR_SIGN 1

/* 车体静止参考姿态相对 JY901S 输出的固定角度偏置，单位 deg。 */
#define APP_JY901S_ROLL_OFFSET_DEG 0.0f
#define APP_JY901S_PITCH_OFFSET_DEG 0.0f
#define APP_JY901S_YAW_OFFSET_DEG 0.0f

#if (APP_JY901S_CALIBRATION_SAMPLE_TARGET == 0U) || \
    (APP_JY901S_CALIBRATION_TIMEOUT_MS == 0U)
#error "JY901S calibration sample target and timeout must be nonzero"
#endif
#if (APP_JY901S_CALIBRATION_ENABLE > 1U) || \
    (APP_JY901S_VOFA_CALIBRATED_ENABLE > 1U)
#error "JY901S calibration switches must be 0U or 1U"
#endif
#if (APP_JY901S_VEHICLE_X_SENSOR_AXIS > 2U) || \
    (APP_JY901S_VEHICLE_Y_SENSOR_AXIS > 2U) || \
    (APP_JY901S_VEHICLE_Z_SENSOR_AXIS > 2U) || \
    (APP_JY901S_VEHICLE_X_SENSOR_AXIS == APP_JY901S_VEHICLE_Y_SENSOR_AXIS) || \
    (APP_JY901S_VEHICLE_X_SENSOR_AXIS == APP_JY901S_VEHICLE_Z_SENSOR_AXIS) || \
    (APP_JY901S_VEHICLE_Y_SENSOR_AXIS == APP_JY901S_VEHICLE_Z_SENSOR_AXIS)
#error "JY901S vehicle axis mapping must be a permutation of sensor axes"
#endif
#if ((APP_JY901S_VEHICLE_X_SENSOR_SIGN != 1) && (APP_JY901S_VEHICLE_X_SENSOR_SIGN != -1)) || \
    ((APP_JY901S_VEHICLE_Y_SENSOR_SIGN != 1) && (APP_JY901S_VEHICLE_Y_SENSOR_SIGN != -1)) || \
    ((APP_JY901S_VEHICLE_Z_SENSOR_SIGN != 1) && (APP_JY901S_VEHICLE_Z_SENSOR_SIGN != -1))
#error "JY901S vehicle axis signs must be 1 or -1"
#endif

#define APP_GRAYSCALE_TASK_PERIOD_MS 10U
#define APP_GRAYSCALE_VOFA_TELEMETRY_ENABLE 0U
#define APP_GRAYSCALE_VOFA_TELEMETRY_INTERVAL_MS 100U

#define APP_TASK_MENU_PAGE_COUNT 5U
#define APP_TASK_MENU_FIRST_TASK_ID 2U
#define APP_TASK_MENU_KEY_DEBOUNCE_MS 120U

#ifndef APP_H723_BUTTON_VOFA_TELEMETRY_ENABLE
#define APP_H723_BUTTON_VOFA_TELEMETRY_ENABLE 0U
#endif
#ifndef APP_H723_BUTTON_VOFA_TELEMETRY_INTERVAL_MS
#define APP_H723_BUTTON_VOFA_TELEMETRY_INTERVAL_MS 20U
#endif
#ifndef APP_H723_BUTTON_TASK_PERIOD_MS
#define APP_H723_BUTTON_TASK_PERIOD_MS 5U
#endif
#ifndef APP_H723_BUTTON_DEBOUNCE_SAMPLES
#define APP_H723_BUTTON_DEBOUNCE_SAMPLES 2U
#endif

#define APP_BNO055_VOFA_TELEMETRY_ENABLE 0U
#define APP_BNO055_VOFA_TELEMETRY_INTERVAL_MS 20U
#define APP_BNO055_TASK_PERIOD_MS 5U
#define APP_BNO055_UART_TIMEOUT_MS 20U
#define APP_BNO055_RETRY_INTERVAL_MS 1000U
#ifndef APP_H723_BNO055_SERVICE_ENABLE
#define APP_H723_BNO055_SERVICE_ENABLE 0U
#endif

/* UART8 DMA/TC completion must arrive well before this software recovery deadline. */
#define APP_H723_UART8_TX_TIMEOUT_MS 20U

/* JY901S 水管倾角外环：仅由 Keil Watch 显式 enable 后接管 ID 3 位置请求。 */
#ifndef APP_H723_TILT_CONTROL_ENABLE
#define APP_H723_TILT_CONTROL_ENABLE 1U
#endif
#define APP_H723_TILT_CONTROL_PERIOD_MS 5U
#define APP_H723_TILT_CONTROL_SAMPLE_MAX_AGE_MS 30U
#define APP_H723_TILT_CONTROL_PITCH_TO_TILT_SIGN -1.0f
#define APP_H723_TILT_CONTROL_PID_KP 120.0f
#define APP_H723_TILT_CONTROL_PID_KI 0.0f
#define APP_H723_TILT_CONTROL_PID_KD 6.0f
#define APP_H723_TILT_CONTROL_PID_DEADBAND_DEG 0.05f
#define APP_H723_TILT_CONTROL_DERIVATIVE_FILTER_N 20.0f
#define APP_H723_TILT_CONTROL_MAX_POSITION_RATE_DEG_S 3000.0f

/* ID 3 water-pipe tilt outer-loop diagnostics, emitted through UART8 VOFA. */
#define APP_H723_TILT_CONTROL_VOFA_TELEMETRY_ENABLE 0U
#define APP_H723_TILT_CONTROL_VOFA_TELEMETRY_INTERVAL_MS 2U

#ifndef APP_H723_K230_UART2_TEST_ENABLE
#define APP_H723_K230_UART2_TEST_ENABLE 0U
#endif

#ifndef APP_H723_BUZZER_TEST_ENABLE
#define APP_H723_BUZZER_TEST_ENABLE 0U
#endif
#ifndef APP_H723_BUZZER_FREQUENCY_HZ
#define APP_H723_BUZZER_FREQUENCY_HZ 2000U
#endif
#ifndef APP_H723_BUZZER_DUTY_PERCENT
#define APP_H723_BUZZER_DUTY_PERCENT 50U
#endif
#ifndef APP_H723_BUZZER_ON_TIME_MS
#define APP_H723_BUZZER_ON_TIME_MS 200U
#endif
#ifndef APP_H723_BUZZER_OFF_TIME_MS
#define APP_H723_BUZZER_OFF_TIME_MS 1800U
#endif

#ifndef APP_H723_K230_UART2_TEST_VOFA_INTERVAL_MS
#define APP_H723_K230_UART2_TEST_VOFA_INTERVAL_MS 20U
#endif

#ifndef APP_H723_OLED_I2C_ADDRESS
#define APP_H723_OLED_I2C_ADDRESS 0x3CU
#endif
#ifndef APP_H723_OLED_TASK_PERIOD_MS
#define APP_H723_OLED_TASK_PERIOD_MS 100U
#endif
#ifndef APP_H723_OLED_REFRESH_PERIOD_MS
#define APP_H723_OLED_REFRESH_PERIOD_MS 100U
#endif
#ifndef APP_H723_OLED_I2C_TIMEOUT_MS
#define APP_H723_OLED_I2C_TIMEOUT_MS 50U
#endif

#ifndef APP_H723_SINGLE_MOTOR_PID_DEBUG_ENABLE
#define APP_H723_SINGLE_MOTOR_PID_DEBUG_ENABLE 0U
#endif

#ifndef APP_H723_SINGLE_MOTOR_DEBUG_DEFAULT_ID
#define APP_H723_SINGLE_MOTOR_DEBUG_DEFAULT_ID 1U
#endif

#ifndef APP_H723_SINGLE_MOTOR_VOFA_TELEMETRY_ENABLE
#define APP_H723_SINGLE_MOTOR_VOFA_TELEMETRY_ENABLE 0U
#endif

#ifndef APP_H723_SINGLE_MOTOR_VOFA_TELEMETRY_INTERVAL_MS
#define APP_H723_SINGLE_MOTOR_VOFA_TELEMETRY_INTERVAL_MS 1U
#endif

#define APP_H723_CHASSIS_VOFA_TELEMETRY_ENABLE 0U
#define APP_H723_CHASSIS_VOFA_TELEMETRY_INTERVAL_MS 20U

#define APP_H723_LINE_FOLLOW_PID_VOFA_TELEMETRY_ENABLE 0U
#define APP_H723_LINE_FOLLOW_PID_VOFA_TELEMETRY_INTERVAL_MS 10U

#if ((APP_VOFA_HEALTH_TELEMETRY_ENABLE == 1U) + \
     (APP_JY901S_VOFA_TELEMETRY_ENABLE == 1U) + \
     (APP_BNO055_VOFA_TELEMETRY_ENABLE == 1U) + \
     (APP_GRAYSCALE_VOFA_TELEMETRY_ENABLE == 1U) + \
     (APP_H723_SINGLE_MOTOR_VOFA_TELEMETRY_ENABLE == 1U) + \
     (APP_H723_K230_UART2_TEST_ENABLE == 1U) + \
     (APP_H723_CHASSIS_VOFA_TELEMETRY_ENABLE == 1U) + \
     (APP_H723_LINE_FOLLOW_PID_VOFA_TELEMETRY_ENABLE == 1U) + \
     (APP_H723_BUTTON_VOFA_TELEMETRY_ENABLE == 1U) + \
     (APP_H723_TILT_CONTROL_VOFA_TELEMETRY_ENABLE == 1U)) > 1U
#error "UART8 VOFA telemetry modes are mutually exclusive"
#endif

#if (APP_H723_TILT_CONTROL_VOFA_TELEMETRY_ENABLE > 1U)
#error "APP_H723_TILT_CONTROL_VOFA_TELEMETRY_ENABLE must be 0U or 1U"
#endif
#if (APP_H723_TILT_CONTROL_VOFA_TELEMETRY_INTERVAL_MS == 0U)
#error "APP_H723_TILT_CONTROL_VOFA_TELEMETRY_INTERVAL_MS must be nonzero"
#endif
#if (APP_H723_UART8_TX_TIMEOUT_MS == 0U)
#error "APP_H723_UART8_TX_TIMEOUT_MS must be nonzero"
#endif

#if (APP_H723_LINE_FOLLOW_PID_VOFA_TELEMETRY_ENABLE > 1U)
#error "APP_H723_LINE_FOLLOW_PID_VOFA_TELEMETRY_ENABLE must be 0U or 1U"
#endif
#if (APP_H723_LINE_FOLLOW_PID_VOFA_TELEMETRY_INTERVAL_MS == 0U)
#error "APP_H723_LINE_FOLLOW_PID_VOFA_TELEMETRY_INTERVAL_MS must be nonzero"
#endif

#if (APP_H723_BUTTON_VOFA_TELEMETRY_ENABLE > 1U)
#error "APP_H723_BUTTON_VOFA_TELEMETRY_ENABLE must be 0U or 1U"
#endif
#if (APP_H723_BUTTON_VOFA_TELEMETRY_INTERVAL_MS == 0U) || \
    (APP_H723_BUTTON_TASK_PERIOD_MS == 0U) || \
    (APP_H723_BUTTON_DEBOUNCE_SAMPLES == 0U)
#error "Button telemetry period, task period, and debounce samples must be nonzero"
#endif

#if (APP_H723_BUZZER_TEST_ENABLE > 1U)
#error "APP_H723_BUZZER_TEST_ENABLE must be 0U or 1U"
#endif
#if (APP_H723_BUZZER_FREQUENCY_HZ < 1000U) || \
    (APP_H723_BUZZER_FREQUENCY_HZ > 20000U)
#error "APP_H723_BUZZER_FREQUENCY_HZ must be between 1000 Hz and 20000 Hz"
#endif
#if (APP_H723_BUZZER_DUTY_PERCENT > 100U)
#error "APP_H723_BUZZER_DUTY_PERCENT must not exceed 100"
#endif
#if (APP_H723_BUZZER_ON_TIME_MS == 0U) || \
    (APP_H723_BUZZER_OFF_TIME_MS == 0U)
#error "APP_H723_BUZZER_ON_TIME_MS and APP_H723_BUZZER_OFF_TIME_MS must be nonzero"
#endif
#if (APP_H723_OLED_I2C_ADDRESS > 0x7FU)
#error "APP_H723_OLED_I2C_ADDRESS must be a 7-bit address"
#endif
#if (APP_H723_OLED_TASK_PERIOD_MS == 0U) || \
    (APP_H723_OLED_REFRESH_PERIOD_MS == 0U) || \
    (APP_H723_OLED_I2C_TIMEOUT_MS == 0U)
#error "OLED task period, refresh period, and I2C timeout must be nonzero"
#endif

#if (APP_H723_SINGLE_MOTOR_VOFA_TELEMETRY_ENABLE == 1U) && \
    (APP_H723_SINGLE_MOTOR_PID_DEBUG_ENABLE != 1U)
#error "Single-motor VOFA telemetry requires APP_H723_SINGLE_MOTOR_PID_DEBUG_ENABLE"
#endif

#if (APP_H723_SINGLE_MOTOR_DEBUG_DEFAULT_ID < 1U) || \
    (APP_H723_SINGLE_MOTOR_DEBUG_DEFAULT_ID > 3U)
#error "APP_H723_SINGLE_MOTOR_DEBUG_DEFAULT_ID must be 1U, 2U, or 3U"
#endif

#define APP_H723_CHASSIS_ACTUATION_ENABLE 1U

#ifndef APP_H723_M2006_FDCAN_INSTANCE
#define APP_H723_M2006_FDCAN_INSTANCE 2U
#endif

#if (APP_H723_M2006_FDCAN_INSTANCE < 1U) || (APP_H723_M2006_FDCAN_INSTANCE > 3U)
#error "APP_H723_M2006_FDCAN_INSTANCE must be 1U, 2U, or 3U"
#endif

#define APP_H723_CHASSIS_TASK_PERIOD_MS 1U
#define APP_H723_CRSF_TIMEOUT_MS 100U
#define APP_H723_CRSF_DEADBAND_NORMALIZED 0.2f
#define APP_H723_CRSF_SE_CHANNEL_INDEX 4U
#define APP_H723_CRSF_SB_CHANNEL_INDEX 6U
#define APP_H723_CRSF_SC_CHANNEL_INDEX 7U
#define APP_H723_M2006_GEAR_RATIO 36.0f
#define APP_H723_M2006_C610_MAX_CURRENT_A 10.0f
#define APP_H723_M2006_CURRENT_MAX_RAW 16384
#define APP_H723_CHASSIS_MAX_OUTPUT_RPM 550.0f
#define APP_H723_LEFT_SIGN 1.0f
#define APP_H723_RIGHT_SIGN -1.0f
#define APP_H723_PI_F 3.14159265358979323846f
#define APP_H723_WHEEL_DIAMETER_MM 65.0f
#define APP_H723_OUTPUT_RPM_TO_MM_S ((APP_H723_WHEEL_DIAMETER_MM * APP_H723_PI_F) / 60.0f)
#define APP_H723_MM_S_TO_OUTPUT_RPM (60.0f / (APP_H723_WHEEL_DIAMETER_MM * APP_H723_PI_F))
#define APP_H723_LINE_FOLLOW_STICK_RANGE_MM_S 1000.0f
#define APP_H723_LINE_FOLLOW_LINE_STRENGTH_MIN 800U
#define APP_H723_LINE_FOLLOW_MAX_TURN_SPEED_MM_S (1000.0f * APP_H723_OUTPUT_RPM_TO_MM_S)
#define APP_H723_LINE_FOLLOW_PID_KP 38.0f
#define APP_H723_LINE_FOLLOW_PID_KI 0.0f
#define APP_H723_LINE_FOLLOW_PID_KD 0.0f
#define APP_H723_LINE_FOLLOW_PID_DEADBAND 0.0f
#define APP_H723_LINE_FOLLOW_TURN_SIGN -1.0f

/* Line-follow PID group identifiers. */
#define APP_H723_LINE_FOLLOW_GROUP_COMMON 0U
#define APP_H723_LINE_FOLLOW_GROUP_TASK2 2U
#define APP_H723_LINE_FOLLOW_GROUP_TASK456 456U

/* Independent line-follow PID parameters for task 2. */
#define APP_H723_TASK2_LINE_FOLLOW_PID_KP 50.0f
#define APP_H723_TASK2_LINE_FOLLOW_PID_KI 0.0f
#define APP_H723_TASK2_LINE_FOLLOW_PID_KD 0.0f
#define APP_H723_TASK2_LINE_FOLLOW_PID_OUTPUT_LIMIT_MM_S \
    APP_H723_LINE_FOLLOW_MAX_TURN_SPEED_MM_S
#define APP_H723_TASK2_LINE_FOLLOW_PID_DEADBAND 0.0f

/* Shared line-follow PID parameters for tasks 4, 5, and 6. */
#define APP_H723_TASK456_LINE_FOLLOW_PID_KP 38.0f
#define APP_H723_TASK456_LINE_FOLLOW_PID_KI 0.0f
#define APP_H723_TASK456_LINE_FOLLOW_PID_KD 0.0f
#define APP_H723_TASK456_LINE_FOLLOW_PID_OUTPUT_LIMIT_MM_S \
    APP_H723_LINE_FOLLOW_MAX_TURN_SPEED_MM_S
#define APP_H723_TASK456_LINE_FOLLOW_PID_DEADBAND 0.0f

/* 任务二固定循迹速度，单位 mm/s。 */
#define APP_H723_TASK2_SPEED_MM_S 360.0f
/* 黑线计数达到该阈值时立即停车。 */
#define APP_H723_TASK2_STOP_BLACK_COUNT 5U

#define APP_H723_TASK4_CRUISE_SPEED_MM_S 350.0f
#define APP_H723_TASK4_ACCEL_MM_S2 100.0f
#define APP_H723_TASK4_DECEL_MM_S2 100.0f
#define APP_H723_TASK4_RUN_TIMEOUT_MS 10000U
#define APP_H723_TASK4_A_TO_B_DISTANCE_MM 1500.0f
#define APP_H723_TASK4_VEHICLE_LENGTH_MM 330.0f

#define APP_H723_TASK56_CRUISE_SPEED_MM_S 220.0f
#define APP_H723_TASK56_ACCEL_MM_S2 100.0f
#define APP_H723_TASK56_DECEL_MM_S2 100.0f
#define APP_H723_TASK56_RUN_TIMEOUT_MS 30000U
#define APP_H723_TASK56_LAP_DISTANCE_MM 6140.0f

#define APP_H723_M2006_FEEDBACK_TIMEOUT_MS 50U
#define APP_H723_M2006_POSITION_TRACKER_MAX_GAP_MS APP_H723_M2006_FEEDBACK_TIMEOUT_MS
#define APP_H723_M2006_CURRENT_LIMIT_A APP_H723_M2006_C610_MAX_CURRENT_A
#define APP_H723_M2006_PID_KP 0.25f
#define APP_H723_M2006_PID_KI 5.0f
#define APP_H723_M2006_PID_KD 0.0f
#define APP_H723_M2006_PID_INTEGRAL_LIMIT 0.0f
#define APP_H723_M2006_PID_OUTPUT_DELTA_LIMIT 0.0f
#define APP_H723_M2006_PID_DEADBAND_RPM 0.1f
#define APP_H723_M2006_PID_INTEGRAL_SEPARATION_RPM 0.0f

/* ID 3 平衡机构专用控制；启用后不允许单电机调试通道接管该电机。 */
#ifndef APP_H723_BALANCE_ENABLE
#define APP_H723_BALANCE_ENABLE 1U
#endif
/* 平衡曲柄固定使用 M2006 CAN ID 3，索引为电流组帧的第三个槽位。 */
#ifndef APP_H723_BALANCE_MOTOR_ID
#define APP_H723_BALANCE_MOTOR_ID 3U
#endif
/* 输出轴右手系的负值：反转搜索并顶住机械限位，单位为输出轴 RPM。 */
#ifndef APP_H723_BALANCE_HOME_SEARCH_OUTPUT_SPEED_RPM
#define APP_H723_BALANCE_HOME_SEARCH_OUTPUT_SPEED_RPM -8.0f
#endif
/* 归零搜索和顶住确认共用的最大电流，直接限制机械限位处的驱动力。 */
#ifndef APP_H723_BALANCE_HOME_CURRENT_LIMIT_A
#define APP_H723_BALANCE_HOME_CURRENT_LIMIT_A 1.0f
#endif
/* 判定顶到限位时允许的最大输出轴速度绝对值，单位为输出轴 RPM。 */
#ifndef APP_H723_BALANCE_HOME_STALL_SPEED_RPM
#define APP_H723_BALANCE_HOME_STALL_SPEED_RPM 1.0f
#endif
/* 实际反馈电流绝对值达到归零限流的此比例后，才允许开始顶住计时。 */
#ifndef APP_H723_BALANCE_HOME_STALL_CURRENT_RATIO
#define APP_H723_BALANCE_HOME_STALL_CURRENT_RATIO 0.80f
#endif
/* 低速且有负载需要连续保持的时间，单位为 ms。 */
#ifndef APP_H723_BALANCE_HOME_CONFIRM_MS
#define APP_H723_BALANCE_HOME_CONFIRM_MS 300U
#endif
/* 从开始反向搜索到判定失败的总超时，单位为 ms；超时后电流清零并锁定故障。 */
#ifndef APP_H723_BALANCE_HOME_TIMEOUT_MS
#define APP_H723_BALANCE_HOME_TIMEOUT_MS 12000U
#endif
/* 归零搜索速度内环 PID；输出和积分上限始终由归零电流上限强制覆盖。 */
#ifndef APP_H723_BALANCE_HOME_SPEED_PID_KP
#define APP_H723_BALANCE_HOME_SPEED_PID_KP 0.25f
#endif
#ifndef APP_H723_BALANCE_HOME_SPEED_PID_KI
#define APP_H723_BALANCE_HOME_SPEED_PID_KI 5.0f
#endif
#ifndef APP_H723_BALANCE_HOME_SPEED_PID_KD
#define APP_H723_BALANCE_HOME_SPEED_PID_KD 0.0f
#endif
/* 软件坐标范围必须包含触限点的 0 deg，不能用此宏设置归零后的安全避让距离。 */
#ifndef APP_H723_BALANCE_POSITION_MIN_DEG
#define APP_H723_BALANCE_POSITION_MIN_DEG 0.0f
#endif
/* 归零后的正常运行安全下限；Watch 目标低于该值会被夹紧，避免再次靠近机械限位。 */
#ifndef APP_H723_BALANCE_POSITION_ACTIVE_MIN_DEG
#define APP_H723_BALANCE_POSITION_ACTIVE_MIN_DEG 70.0f
#endif
/* 曲柄从软件零位向正方向的首次保守行程上限，单位为输出轴 deg。 */
#ifndef APP_H723_BALANCE_POSITION_MAX_DEG
#define APP_H723_BALANCE_POSITION_MAX_DEG 210.0f
#endif
/* Watch extended-range mode remains bounded by these separately validated soft limits. */
#ifndef APP_H723_BALANCE_POSITION_DEBUG_ACTIVE_MIN_DEG
#define APP_H723_BALANCE_POSITION_DEBUG_ACTIVE_MIN_DEG 0.0f
#endif
#ifndef APP_H723_BALANCE_POSITION_DEBUG_MAX_DEG
#define APP_H723_BALANCE_POSITION_DEBUG_MAX_DEG 360.0f
#endif
/* 位置外环更新周期，单位为 ms；速度内环固定由 1 ms 底盘任务执行。 */
#ifndef APP_H723_BALANCE_POSITION_PERIOD_MS
#define APP_H723_BALANCE_POSITION_PERIOD_MS 5U
#endif
/* 位置外环输出的最大目标速度，单位为输出轴 RPM。 */
#ifndef APP_H723_BALANCE_POSITION_MAX_OUTPUT_SPEED_RPM
#define APP_H723_BALANCE_POSITION_MAX_OUTPUT_SPEED_RPM 550.0f
#endif
/* 正常位置控制的电流上限；与归零限流分开，仍保持 3D 打印机构的保守值。 */
#ifndef APP_H723_BALANCE_POSITION_CURRENT_LIMIT_A
#define APP_H723_BALANCE_POSITION_CURRENT_LIMIT_A 10.0f
#endif
/* 归零后位置控制使用的速度内环 PID。 */
#ifndef APP_H723_BALANCE_POSITION_SPEED_PID_KP
#define APP_H723_BALANCE_POSITION_SPEED_PID_KP 0.25f
#endif
#ifndef APP_H723_BALANCE_POSITION_SPEED_PID_KI
#define APP_H723_BALANCE_POSITION_SPEED_PID_KI 5.0f
#endif
#ifndef APP_H723_BALANCE_POSITION_SPEED_PID_KD
#define APP_H723_BALANCE_POSITION_SPEED_PID_KD 0.0f
#endif
/* 输出轴位置外环 PID，输入与反馈单位均为相对软件零位的 deg。 */
#ifndef APP_H723_BALANCE_POSITION_PID_KP
#define APP_H723_BALANCE_POSITION_PID_KP 2.0f
#endif
#ifndef APP_H723_BALANCE_POSITION_PID_KI
#define APP_H723_BALANCE_POSITION_PID_KI 0.0f
#endif
#ifndef APP_H723_BALANCE_POSITION_PID_KD
#define APP_H723_BALANCE_POSITION_PID_KD 0.0f
#endif

#if (APP_H723_BALANCE_ENABLE != 0U) && (APP_H723_BALANCE_ENABLE != 1U)
#error "APP_H723_BALANCE_ENABLE must be 0U or 1U"
#endif
#if (APP_H723_TILT_CONTROL_ENABLE != 0U) && (APP_H723_TILT_CONTROL_ENABLE != 1U)
#error "APP_H723_TILT_CONTROL_ENABLE must be 0U or 1U"
#endif
#if (APP_H723_BNO055_SERVICE_ENABLE != 0U) && (APP_H723_BNO055_SERVICE_ENABLE != 1U)
#error "APP_H723_BNO055_SERVICE_ENABLE must be 0U or 1U"
#endif
#if (APP_BNO055_VOFA_TELEMETRY_ENABLE == 1U) && (APP_H723_BNO055_SERVICE_ENABLE != 1U)
#error "BNO055 VOFA telemetry requires APP_H723_BNO055_SERVICE_ENABLE"
#endif
#if (APP_H723_TILT_CONTROL_PERIOD_MS == 0U) || \
    (APP_H723_TILT_CONTROL_SAMPLE_MAX_AGE_MS < APP_H723_TILT_CONTROL_PERIOD_MS)
#error "Tilt control timing configuration is invalid"
#endif
#if (APP_H723_BALANCE_MOTOR_ID != 3U)
#error "APP_H723_BALANCE_MOTOR_ID must remain 3U"
#endif
#if (APP_H723_BALANCE_HOME_CONFIRM_MS == 0U) || \
    (APP_H723_BALANCE_HOME_TIMEOUT_MS <= APP_H723_BALANCE_HOME_CONFIRM_MS)
#error "Balance homing timeouts are invalid"
#endif
#if (APP_H723_BALANCE_POSITION_PERIOD_MS == 0U)
#error "Balance position loop configuration is invalid"
#endif
#if (APP_H723_BALANCE_ENABLE == 1U) && \
    (APP_H723_SINGLE_MOTOR_DEBUG_DEFAULT_ID == APP_H723_BALANCE_MOTOR_ID)
#error "Single motor debug default cannot claim the balance motor"
#endif

#define APP_H723_SINGLE_MOTOR_MAX_OUTPUT_RPM APP_H723_CHASSIS_MAX_OUTPUT_RPM
#define APP_H723_SINGLE_MOTOR_POSITION_PID_PERIOD_MS 5U
#define APP_H723_SINGLE_MOTOR_POSITION_PID_KP 20.0f
#define APP_H723_SINGLE_MOTOR_POSITION_PID_KI 0.0f
#define APP_H723_SINGLE_MOTOR_POSITION_PID_KD 0.0f
#define APP_H723_SINGLE_MOTOR_POSITION_PID_OUTPUT_LIMIT_RPM APP_H723_SINGLE_MOTOR_MAX_OUTPUT_RPM
#define APP_H723_SINGLE_MOTOR_POSITION_PID_DEADBAND_DEG 0.0f

#endif
