#ifndef APP_CONFIG_H
#define APP_CONFIG_H

/* Application-wide compile-time configuration. Build defines override defaults. */

#ifndef APP_RTOS_MONITOR_ENABLE
#define APP_RTOS_MONITOR_ENABLE 1U
#endif
#ifndef APP_OLED_TEST_TASK_ENABLE
#define APP_OLED_TEST_TASK_ENABLE 0U
#endif
#ifndef APP_OLED_I2C_ADDRESS
#define APP_OLED_I2C_ADDRESS 0x3CU
#endif
#ifndef APP_SERVO_FEATURE_ENABLE
#define APP_SERVO_FEATURE_ENABLE 0U
#endif
#ifndef APP_SERVO_MAX_ANGLE_DEG
#define APP_SERVO_MAX_ANGLE_DEG 180U
#endif
#ifndef APP_SERVO_INITIAL_ANGLE_DEG
#define APP_SERVO_INITIAL_ANGLE_DEG 90U
#endif
#ifndef APP_SERVO_MIN_PULSE_US
#define APP_SERVO_MIN_PULSE_US 500U
#endif
#ifndef APP_SERVO_MAX_PULSE_US
#define APP_SERVO_MAX_PULSE_US 2500U
#endif
#ifndef APP_SERVO_TASK_INTERVAL_MS
#define APP_SERVO_TASK_INTERVAL_MS 20U
#endif

#ifndef APP_TASK_PRIORITY
#define APP_TASK_PRIORITY 1U
#endif
#ifndef APP_TELEMETRY_TASK_PRIORITY
#define APP_TELEMETRY_TASK_PRIORITY 0U
#endif
#ifndef APP_MOTOR_TASK_STACK_DEPTH
#define APP_MOTOR_TASK_STACK_DEPTH 256U
#endif
#ifndef APP_WS2812_TASK_STACK_DEPTH
#define APP_WS2812_TASK_STACK_DEPTH 256U
#endif
#ifndef APP_OLED_TEST_TASK_STACK_DEPTH
#define APP_OLED_TEST_TASK_STACK_DEPTH 384U
#endif
#ifndef APP_UART_TASK_STACK_DEPTH
#define APP_UART_TASK_STACK_DEPTH 256U
#endif
#ifndef APP_UART_TX_TASK_STACK_DEPTH
#define APP_UART_TX_TASK_STACK_DEPTH 256U
#endif
#ifndef APP_BUZZER_TASK_STACK_DEPTH
#define APP_BUZZER_TASK_STACK_DEPTH 128U
#endif
#ifndef APP_SERVO_TASK_STACK_DEPTH
#define APP_SERVO_TASK_STACK_DEPTH 128U
#endif
#ifndef APP_BUTTON_TASK_STACK_DEPTH
#define APP_BUTTON_TASK_STACK_DEPTH 128U
#endif
#ifndef APP_UART_RX_QUEUE_LENGTH
#define APP_UART_RX_QUEUE_LENGTH 64U
#endif
#ifndef APP_CRSF_TASK_STACK_DEPTH
#define APP_CRSF_TASK_STACK_DEPTH 256U
#endif
#ifndef APP_WS2812_BRIGHTNESS
#define APP_WS2812_BRIGHTNESS 16U
#endif
#ifndef APP_WS2812_ANIMATION_ENABLE
#define APP_WS2812_ANIMATION_ENABLE 0U
#endif
#ifndef APP_WS2812_STATUS_INDICATOR_ENABLE
#define APP_WS2812_STATUS_INDICATOR_ENABLE 1U
#endif
#ifndef APP_BUTTON_TASK_INTERVAL_MS
#define APP_BUTTON_TASK_INTERVAL_MS 10U
#endif
#ifndef APP_RTOS_MONITOR_TASK_STACK_DEPTH
#define APP_RTOS_MONITOR_TASK_STACK_DEPTH 512U
#endif

#ifndef APP_VOFA_SPEED_PID_TELEMETRY_ENABLE
#define APP_VOFA_SPEED_PID_TELEMETRY_ENABLE 0U
#endif
#ifndef APP_VOFA_SPEED_PID_TELEMETRY_INTERVAL_MS
#define APP_VOFA_SPEED_PID_TELEMETRY_INTERVAL_MS 10U
#endif
#ifndef APP_VOFA_SPEED_PID_TELEMETRY_TASK_STACK_DEPTH
#define APP_VOFA_SPEED_PID_TELEMETRY_TASK_STACK_DEPTH 256U
#endif
#ifndef APP_VOFA_SPEED_PID_TELEMETRY_TASK_PRIORITY
#define APP_VOFA_SPEED_PID_TELEMETRY_TASK_PRIORITY 0U
#endif

#ifndef APP_GRAY_VOFA_TELEMETRY_ENABLE
#define APP_GRAY_VOFA_TELEMETRY_ENABLE 0U
#endif
#ifndef APP_GRAY_VOFA_TELEMETRY_INTERVAL_MS
#define APP_GRAY_VOFA_TELEMETRY_INTERVAL_MS 100U
#endif
#ifndef APP_GRAY_VOFA_CHANNEL_COUNT
#define APP_GRAY_VOFA_CHANNEL_COUNT 22U
#endif

#ifndef APP_LINE_CONTROL_VOFA_TELEMETRY_ENABLE
#define APP_LINE_CONTROL_VOFA_TELEMETRY_ENABLE 0U
#endif
#ifndef APP_LINE_CONTROL_VOFA_TELEMETRY_INTERVAL_MS
#define APP_LINE_CONTROL_VOFA_TELEMETRY_INTERVAL_MS 20U
#endif
#ifndef APP_LINE_CONTROL_VOFA_TELEMETRY_TASK_STACK_DEPTH
#define APP_LINE_CONTROL_VOFA_TELEMETRY_TASK_STACK_DEPTH 256U
#endif
#ifndef APP_LINE_CONTROL_CHANNEL_COUNT
#define APP_LINE_CONTROL_CHANNEL_COUNT 18U
#endif

#ifndef APP_IMU_TELEMETRY_ENABLE
#define APP_IMU_TELEMETRY_ENABLE 0U
#endif
#ifndef APP_IMU_VOFA_TELEMETRY_INTERVAL_MS
#define APP_IMU_VOFA_TELEMETRY_INTERVAL_MS 10U
#endif
#ifndef APP_IMU_VOFA_TELEMETRY_TASK_STACK_DEPTH
#define APP_IMU_VOFA_TELEMETRY_TASK_STACK_DEPTH 256U
#endif
#ifndef APP_IMU_YAW_ENABLE
#define APP_IMU_YAW_ENABLE 1U
#endif
#ifndef APP_IMU_YAW_TRACK_WIDTH_MM
#define APP_IMU_YAW_TRACK_WIDTH_MM 130.0f
#endif
#ifndef APP_IMU_TASK_STACK_DEPTH
#define APP_IMU_TASK_STACK_DEPTH 512U
#endif
#ifndef APP_IMU_TASK_PRIORITY
#define APP_IMU_TASK_PRIORITY 0U
#endif
#ifndef APP_IMU_SAMPLE_INTERVAL_MS
#define APP_IMU_SAMPLE_INTERVAL_MS 10U
#endif
#ifndef APP_IMU_REINIT_FAILURE_THRESHOLD
#define APP_IMU_REINIT_FAILURE_THRESHOLD 3U
#endif
#ifndef APP_GRAY_SAMPLE_INTERVAL_MS
#define APP_GRAY_SAMPLE_INTERVAL_MS 10U
#endif
#ifndef APP_LINE_CONTROL_INTERVAL_MS
#define APP_LINE_CONTROL_INTERVAL_MS 50U
#endif
#ifndef APP_YAW_CONTROL_INTERVAL_MS
#define APP_YAW_CONTROL_INTERVAL_MS 50U
#endif
#ifndef APP_GRAY_TASK_STACK_DEPTH
#define APP_GRAY_TASK_STACK_DEPTH 512U
#endif

#ifndef APP_BUTTON_FEATURE_ENABLE
#define APP_BUTTON_FEATURE_ENABLE 0U
#endif
#ifndef APP_BUZZER_FEATURE_ENABLE
#define APP_BUZZER_FEATURE_ENABLE 0U
#endif
#ifndef APP_BUZZER_FREQUENCY_HZ
#define APP_BUZZER_FREQUENCY_HZ 2000U
#endif
#ifndef APP_BUZZER_DUTY_PERCENT
#define APP_BUZZER_DUTY_PERCENT 50U
#endif
#ifndef APP_BUZZER_ON_TIME_MS
#define APP_BUZZER_ON_TIME_MS 200U
#endif
#ifndef APP_BUZZER_OFF_TIME_MS
#define APP_BUZZER_OFF_TIME_MS 1800U
#endif

#if (APP_RTOS_MONITOR_ENABLE > 1U) || (APP_OLED_TEST_TASK_ENABLE > 1U) || \
    (APP_SERVO_FEATURE_ENABLE > 1U) || (APP_BUTTON_FEATURE_ENABLE > 1U) || \
    (APP_BUZZER_FEATURE_ENABLE > 1U) || (APP_VOFA_SPEED_PID_TELEMETRY_ENABLE > 1U) || \
    (APP_GRAY_VOFA_TELEMETRY_ENABLE > 1U) || (APP_IMU_TELEMETRY_ENABLE > 1U) || \
    (APP_LINE_CONTROL_VOFA_TELEMETRY_ENABLE > 1U) || \
    (APP_IMU_YAW_ENABLE > 1U) || (APP_WS2812_ANIMATION_ENABLE > 1U) || \
    (APP_WS2812_STATUS_INDICATOR_ENABLE > 1U)
#error "Application feature switches must be 0U or 1U"
#endif

#if APP_WS2812_ANIMATION_ENABLE && APP_WS2812_STATUS_INDICATOR_ENABLE
#error "WS2812 animation and status indicator cannot be enabled together"
#endif

#if (APP_SERVO_MAX_ANGLE_DEG == 0U)
#error "APP_SERVO_MAX_ANGLE_DEG must be nonzero"
#endif
#if (APP_SERVO_MIN_PULSE_US >= APP_SERVO_MAX_PULSE_US)
#error "APP_SERVO_MIN_PULSE_US must be less than APP_SERVO_MAX_PULSE_US"
#endif
#if (APP_SERVO_INITIAL_ANGLE_DEG > APP_SERVO_MAX_ANGLE_DEG)
#error "APP_SERVO_INITIAL_ANGLE_DEG must not exceed APP_SERVO_MAX_ANGLE_DEG"
#endif
#if (APP_SERVO_MAX_PULSE_US >= 20000U)
#error "APP_SERVO_MAX_PULSE_US must fit inside the 20 ms servo period"
#endif
#if (APP_SERVO_TASK_INTERVAL_MS == 0U)
#error "APP_SERVO_TASK_INTERVAL_MS must be nonzero"
#endif

#if (APP_BUZZER_FREQUENCY_HZ < 1000U) || (APP_BUZZER_FREQUENCY_HZ > 20000U)
#error "APP_BUZZER_FREQUENCY_HZ must be between 1000 Hz and 20000 Hz"
#endif
#if (APP_BUZZER_DUTY_PERCENT > 100U)
#error "APP_BUZZER_DUTY_PERCENT must not exceed 100"
#endif
#if (APP_BUZZER_ON_TIME_MS == 0U) || (APP_BUZZER_OFF_TIME_MS == 0U)
#error "APP_BUZZER_ON_TIME_MS and APP_BUZZER_OFF_TIME_MS must be nonzero"
#endif

#if (APP_VOFA_SPEED_PID_TELEMETRY_ENABLE && \
     (APP_IMU_TELEMETRY_ENABLE || APP_GRAY_VOFA_TELEMETRY_ENABLE || \
      APP_LINE_CONTROL_VOFA_TELEMETRY_ENABLE)) || \
    (APP_GRAY_VOFA_TELEMETRY_ENABLE && \
     (APP_IMU_TELEMETRY_ENABLE || APP_LINE_CONTROL_VOFA_TELEMETRY_ENABLE)) || \
    (APP_IMU_TELEMETRY_ENABLE && APP_LINE_CONTROL_VOFA_TELEMETRY_ENABLE)
#error "VOFA telemetry modes cannot be enabled together"
#endif
#if (APP_IMU_TELEMETRY_ENABLE && APP_GRAY_VOFA_TELEMETRY_ENABLE)
#error "IMU and grayscale telemetry cannot be enabled together"
#endif
#if (APP_IMU_TELEMETRY_ENABLE && !APP_IMU_YAW_ENABLE)
#error "IMU telemetry requires IMU yaw to be enabled"
#endif

#if (APP_TASK_PRIORITY == 0U) || (APP_TELEMETRY_TASK_PRIORITY > APP_TASK_PRIORITY)
#error "Application task priorities are invalid"
#endif
#if (APP_MOTOR_TASK_STACK_DEPTH == 0U) || (APP_WS2812_TASK_STACK_DEPTH == 0U) || \
    (APP_OLED_TEST_TASK_STACK_DEPTH == 0U) || (APP_UART_TASK_STACK_DEPTH == 0U) || \
    (APP_UART_TX_TASK_STACK_DEPTH == 0U) || (APP_BUZZER_TASK_STACK_DEPTH == 0U) || \
    (APP_SERVO_TASK_STACK_DEPTH == 0U) || (APP_BUTTON_TASK_STACK_DEPTH == 0U) || \
    (APP_UART_RX_QUEUE_LENGTH == 0U) || (APP_CRSF_TASK_STACK_DEPTH == 0U) || \
    (APP_RTOS_MONITOR_TASK_STACK_DEPTH == 0U) || \
    (APP_VOFA_SPEED_PID_TELEMETRY_TASK_STACK_DEPTH == 0U) || \
    (APP_LINE_CONTROL_VOFA_TELEMETRY_TASK_STACK_DEPTH == 0U) || \
    (APP_IMU_VOFA_TELEMETRY_TASK_STACK_DEPTH == 0U) || \
    (APP_IMU_TASK_STACK_DEPTH == 0U) || (APP_GRAY_TASK_STACK_DEPTH == 0U)
#error "Application task resources must be nonzero"
#endif
#if (APP_VOFA_SPEED_PID_TELEMETRY_INTERVAL_MS == 0U) || \
    (APP_GRAY_VOFA_TELEMETRY_INTERVAL_MS == 0U) || \
    (APP_LINE_CONTROL_VOFA_TELEMETRY_INTERVAL_MS == 0U) || \
    (APP_IMU_VOFA_TELEMETRY_INTERVAL_MS == 0U) || \
    (APP_SERVO_TASK_INTERVAL_MS == 0U) || \
    (APP_IMU_SAMPLE_INTERVAL_MS == 0U) || (APP_GRAY_SAMPLE_INTERVAL_MS == 0U) || \
    (APP_LINE_CONTROL_INTERVAL_MS == 0U) || (APP_YAW_CONTROL_INTERVAL_MS == 0U) || \
    (APP_IMU_REINIT_FAILURE_THRESHOLD == 0U) || (APP_BUTTON_TASK_INTERVAL_MS == 0U)
#error "Application task intervals and thresholds must be nonzero"
#endif

#endif
