#ifndef ENCODER_CONFIG_H
#define ENCODER_CONFIG_H

/* Encoder mechanics and compile-time decode configuration. */
#ifndef BOARD_ENCODER_MOTOR_LINES_PER_REVOLUTION
#define BOARD_ENCODER_MOTOR_LINES_PER_REVOLUTION 13U
#endif
#ifndef BOARD_ENCODER_GEAR_RATIO
#define BOARD_ENCODER_GEAR_RATIO 20U
#endif

#define BOARD_ENCODER_OUTPUT_SHAFT_LINES_PER_REVOLUTION \
    (BOARD_ENCODER_MOTOR_LINES_PER_REVOLUTION * BOARD_ENCODER_GEAR_RATIO)

#define BOARD_ENCODER_DECODE_MODE_A_PHASE_DUAL_EDGE 1U
#define BOARD_ENCODER_DECODE_MODE_AB_PHASE_QUADRATURE_X4 2U
#define BOARD_ENCODER_A_PHASE_DUAL_EDGE_MULTIPLIER 2U
#define BOARD_ENCODER_AB_PHASE_QUADRATURE_X4_MULTIPLIER 4U

#ifndef BOARD_ENCODER_DECODE_MODE
#define BOARD_ENCODER_DECODE_MODE BOARD_ENCODER_DECODE_MODE_A_PHASE_DUAL_EDGE
#endif
#ifndef BOARD_ENCODER_FRONT_LEFT_DIRECTION_SIGN
#define BOARD_ENCODER_FRONT_LEFT_DIRECTION_SIGN -1
#endif
#ifndef BOARD_ENCODER_FRONT_RIGHT_DIRECTION_SIGN
#define BOARD_ENCODER_FRONT_RIGHT_DIRECTION_SIGN 1
#endif
#ifndef BOARD_ENCODER_REAR_LEFT_DIRECTION_SIGN
#define BOARD_ENCODER_REAR_LEFT_DIRECTION_SIGN 1
#endif
#ifndef BOARD_ENCODER_REAR_RIGHT_DIRECTION_SIGN
#define BOARD_ENCODER_REAR_RIGHT_DIRECTION_SIGN -1
#endif
#ifndef BOARD_ENCODER_WHEEL_DIAMETER_MM
#define BOARD_ENCODER_WHEEL_DIAMETER_MM 48U
#endif
#ifndef BOARD_ENCODER_SAMPLE_PERIOD_MS
#define BOARD_ENCODER_SAMPLE_PERIOD_MS 10U
#endif

#if (BOARD_ENCODER_MOTOR_LINES_PER_REVOLUTION == 0U) || \
    (BOARD_ENCODER_GEAR_RATIO == 0U) || \
    (BOARD_ENCODER_WHEEL_DIAMETER_MM == 0U) || \
    (BOARD_ENCODER_SAMPLE_PERIOD_MS == 0U)
#error "Encoder mechanics and sample period must be nonzero"
#endif

#if BOARD_ENCODER_DECODE_MODE == BOARD_ENCODER_DECODE_MODE_A_PHASE_DUAL_EDGE
#define BOARD_ENCODER_DECODE_MULTIPLIER BOARD_ENCODER_A_PHASE_DUAL_EDGE_MULTIPLIER
#elif BOARD_ENCODER_DECODE_MODE == BOARD_ENCODER_DECODE_MODE_AB_PHASE_QUADRATURE_X4
#define BOARD_ENCODER_DECODE_MULTIPLIER BOARD_ENCODER_AB_PHASE_QUADRATURE_X4_MULTIPLIER
#else
#error "Unsupported board encoder decode mode"
#endif

#if ((BOARD_ENCODER_FRONT_LEFT_DIRECTION_SIGN != 1) && \
     (BOARD_ENCODER_FRONT_LEFT_DIRECTION_SIGN != -1)) || \
    ((BOARD_ENCODER_FRONT_RIGHT_DIRECTION_SIGN != 1) && \
     (BOARD_ENCODER_FRONT_RIGHT_DIRECTION_SIGN != -1)) || \
    ((BOARD_ENCODER_REAR_LEFT_DIRECTION_SIGN != 1) && \
     (BOARD_ENCODER_REAR_LEFT_DIRECTION_SIGN != -1)) || \
    ((BOARD_ENCODER_REAR_RIGHT_DIRECTION_SIGN != 1) && \
     (BOARD_ENCODER_REAR_RIGHT_DIRECTION_SIGN != -1))
#error "Encoder direction signs must be either +1 or -1"
#endif

#define BOARD_ENCODER_COUNTS_PER_REVOLUTION \
    (BOARD_ENCODER_OUTPUT_SHAFT_LINES_PER_REVOLUTION * BOARD_ENCODER_DECODE_MULTIPLIER)

#endif
