#ifndef MOTOR_CONFIG_H
#define MOTOR_CONFIG_H

/* Per-wheel motor polarity relative to the logical forward direction. */
#ifndef BOARD_MOTOR_FRONT_LEFT_DIRECTION_SIGN
#define BOARD_MOTOR_FRONT_LEFT_DIRECTION_SIGN -1
#endif
#ifndef BOARD_MOTOR_FRONT_RIGHT_DIRECTION_SIGN
#define BOARD_MOTOR_FRONT_RIGHT_DIRECTION_SIGN -1
#endif
#ifndef BOARD_MOTOR_REAR_LEFT_DIRECTION_SIGN
#define BOARD_MOTOR_REAR_LEFT_DIRECTION_SIGN -1
#endif
#ifndef BOARD_MOTOR_REAR_RIGHT_DIRECTION_SIGN
#define BOARD_MOTOR_REAR_RIGHT_DIRECTION_SIGN 1
#endif

#if ((BOARD_MOTOR_FRONT_LEFT_DIRECTION_SIGN != 1) && \
     (BOARD_MOTOR_FRONT_LEFT_DIRECTION_SIGN != -1)) || \
    ((BOARD_MOTOR_FRONT_RIGHT_DIRECTION_SIGN != 1) && \
     (BOARD_MOTOR_FRONT_RIGHT_DIRECTION_SIGN != -1)) || \
    ((BOARD_MOTOR_REAR_LEFT_DIRECTION_SIGN != 1) && \
     (BOARD_MOTOR_REAR_LEFT_DIRECTION_SIGN != -1)) || \
    ((BOARD_MOTOR_REAR_RIGHT_DIRECTION_SIGN != 1) && \
     (BOARD_MOTOR_REAR_RIGHT_DIRECTION_SIGN != -1))
#error "Motor direction signs must be either +1 or -1"
#endif

#endif
